CREATE TABLE IF NOT EXISTS coach_interactions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(64) NOT NULL,
    user_id BIGINT NULL,
    http_session_id VARCHAR(128) NULL,
    answer_session_id VARCHAR(64) NULL,
    answer_attempt_no INT NULL,
    attempt_context_type VARCHAR(24) NULL,
    prompt_id VARCHAR(64) NOT NULL,
    prompt_topic VARCHAR(120) NOT NULL,
    prompt_difficulty VARCHAR(8) NOT NULL,
    prompt_question_en TEXT NOT NULL,
    prompt_question_ko TEXT NOT NULL,
    prompt_tip TEXT NOT NULL,
    prompt_hints_json JSON NOT NULL,
    user_question TEXT NOT NULL,
    normalized_question TEXT NOT NULL,
    answer_snapshot TEXT NULL,
    query_mode VARCHAR(32) NOT NULL,
    meaning_family VARCHAR(48) NULL,
    analysis_payload_json JSON NOT NULL,
    coach_reply TEXT NOT NULL,
    expressions_json JSON NOT NULL,
    response_source VARCHAR(48) NOT NULL,
    response_model VARCHAR(64) NULL,
    usage_payload_json JSON NULL,
    used_expressions_json JSON NULL,
    evaluation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_EVALUATED',
    evaluation_score INT NULL,
    evaluation_verdict VARCHAR(48) NULL,
    evaluation_summary TEXT NULL,
    evaluation_model VARCHAR(64) NULL,
    evaluation_payload_json JSON NULL,
    evaluated_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_coach_interactions_request_id (request_id),
    KEY idx_coach_interactions_prompt_created (prompt_id, created_at),
    KEY idx_coach_interactions_user_created (user_id, created_at),
    KEY idx_coach_interactions_eval_status_created (evaluation_status, created_at),
    KEY idx_coach_interactions_answer_session (answer_session_id)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
