CREATE TABLE IF NOT EXISTS feedback_diagnosis_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    answer_attempt_id BIGINT NULL,
    session_id VARCHAR(64) NULL,
    attempt_no INT NULL,
    attempt_type VARCHAR(24) NULL,
    user_id BIGINT NULL,
    guest_id VARCHAR(64) NULL,
    prompt_id VARCHAR(64) NOT NULL,
    prompt_topic VARCHAR(160) NOT NULL,
    prompt_topic_category VARCHAR(120) NULL,
    prompt_topic_detail VARCHAR(160) NULL,
    prompt_difficulty VARCHAR(16) NOT NULL,
    prompt_question_en TEXT NOT NULL,
    prompt_question_ko TEXT NOT NULL,
    prompt_hints_json JSON NULL,
    prompt_task_meta_json JSON NULL,
    learner_answer TEXT NOT NULL,
    previous_answer TEXT NULL,
    llm_provider VARCHAR(32) NOT NULL,
    llm_model VARCHAR(64) NULL,
    diagnosis_response_status_code INT NULL,
    generation_response_status_code INT NULL,
    regeneration_response_status_code INT NULL,
    authoritative_feedback BIT(1) NOT NULL,
    diagnosis_fallback_used BIT(1) NOT NULL,
    deterministic_response_fallback_used BIT(1) NOT NULL,
    retry_attempted BIT(1) NOT NULL,
    diagnosis_score INT NULL,
    diagnosis_answer_band VARCHAR(32) NULL,
    diagnosis_task_completion VARCHAR(16) NULL,
    diagnosis_on_topic BIT(1) NULL,
    diagnosis_finishable BIT(1) NULL,
    diagnosis_grammar_severity VARCHAR(16) NULL,
    diagnosis_grammar_issue_count INT NULL,
    diagnosis_primary_issue_code VARCHAR(96) NULL,
    diagnosis_secondary_issue_code VARCHAR(96) NULL,
    diagnosis_minimal_correction TEXT NULL,
    rewrite_target_action VARCHAR(64) NULL,
    rewrite_target_skeleton TEXT NULL,
    rewrite_target_max_new_sentence_count INT NULL,
    expansion_budget VARCHAR(32) NULL,
    profile_task_answer_band VARCHAR(32) NULL,
    profile_task_completion VARCHAR(16) NULL,
    profile_task_finishable BIT(1) NULL,
    profile_grammar_severity VARCHAR(16) NULL,
    profile_grammar_issue_count INT NULL,
    profile_content_specificity VARCHAR(16) NULL,
    profile_has_main_answer BIT(1) NULL,
    profile_has_reason BIT(1) NULL,
    profile_has_example BIT(1) NULL,
    profile_has_feeling BIT(1) NULL,
    profile_has_activity BIT(1) NULL,
    profile_has_time_or_place BIT(1) NULL,
    diagnosis_payload_json JSON NULL,
    answer_profile_json JSON NULL,
    section_policy_json JSON NULL,
    final_sections_json JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_feedback_diag_prompt_created (prompt_id, created_at),
    KEY idx_feedback_diag_session_attempt (session_id, attempt_no),
    KEY idx_feedback_diag_answer_attempt (answer_attempt_id),
    KEY idx_feedback_diag_band_created (diagnosis_answer_band, created_at)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
