-- Polish active prompt question English so awkward generated phrasing reads naturally.
-- Generated by scripts/generate_active_prompt_question_polish_039.py

UPDATE prompts
SET question_en = 'How do you usually start your Saturdays?'
WHERE id = 'prompt-routine-21'
  AND question_en = 'How do you usually spend the start of your Saturday?';

UPDATE prompts
SET question_en = 'What do you usually do before bed?'
WHERE id = 'prompt-routine-26'
  AND question_en = 'How do you usually spend your time before bed?';

UPDATE prompts
SET question_en = 'What do you usually do during your commute?'
WHERE id = 'prompt-routine-31'
  AND question_en = 'How do you usually spend your time on your commute?';

UPDATE prompts
SET question_en = 'How do you usually spend your lunch break?'
WHERE id = 'prompt-routine-36'
  AND question_en = 'How do you usually spend your time during your lunch break?';

UPDATE prompts
SET question_en = 'What do you usually do on rainy days at home?'
WHERE id = 'prompt-routine-41'
  AND question_en = 'How do you usually spend your time on rainy days at home?';

UPDATE prompts
SET question_en = 'What do you usually do right after you wake up?'
WHERE id = 'prompt-routine-46'
  AND question_en = 'How do you usually spend your time right after waking up?';

UPDATE prompts
SET question_en = 'What do you usually do on laundry day at home, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1101'
  AND question_en = 'What do you usually do on laundry day at home, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do before an early appointment, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1102'
  AND question_en = 'Describe what you usually do before an early appointment, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'After grocery shopping, what do you usually do, and why?'
WHERE id = 'prompt-routine-1103'
  AND question_en = 'When it is after grocery shopping, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What do you usually do while waiting for class to begin, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1104'
  AND question_en = 'What do you usually do while waiting for class to begin, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do during your first hour at work, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1105'
  AND question_en = 'Describe what you usually do during your first hour at work, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'On a quiet Sunday evening, what do you usually do, and why?'
WHERE id = 'prompt-routine-1106'
  AND question_en = 'When it is on a quiet Sunday evening, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What do you usually do before meeting friends for dinner, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1107'
  AND question_en = 'What do you usually do before meeting friends for dinner, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do after finishing a workout, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1108'
  AND question_en = 'Describe what you usually do after finishing a workout, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'During a long train ride, what do you usually do, and why?'
WHERE id = 'prompt-routine-1109'
  AND question_en = 'When it is during a long train ride, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What do you usually do on a day when you stay indoors, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1110'
  AND question_en = 'What do you usually do on a day when you stay indoors, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do while preparing for an exam, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1111'
  AND question_en = 'Describe what you usually do while preparing for an exam, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'After a late lunch, what do you usually do, and why?'
WHERE id = 'prompt-routine-1112'
  AND question_en = 'When it is after a late lunch, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What do you usually do when you clean your room, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1113'
  AND question_en = 'What do you usually do when you clean your room, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do on Friday night at home, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1114'
  AND question_en = 'Describe what you usually do on Friday night at home, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'Before a family outing, what do you usually do, and why?'
WHERE id = 'prompt-routine-1115'
  AND question_en = 'When it is before a family outing, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What do you usually do on weekend evenings, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1116'
  AND question_en = 'What do you usually do during your weekend evening, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do when you arrive somewhere too early, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1117'
  AND question_en = 'Describe what you usually do when you arrive somewhere too early, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'After a shopping trip, what do you usually do, and why?'
WHERE id = 'prompt-routine-1118'
  AND question_en = 'When it is after coming back from a shopping trip, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What do you usually do before leaving for school, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1119'
  AND question_en = 'What do you usually do before leaving for school, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do while riding the subway alone, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1120'
  AND question_en = 'Describe what you usually do while riding the subway alone, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'After finishing your household chores, what do you usually do, and why?'
WHERE id = 'prompt-routine-1121'
  AND question_en = 'When it is after finishing household chores, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What do you usually do on a rainy morning indoors, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1122'
  AND question_en = 'What do you usually do on a rainy morning indoors, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do before starting a side project, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1123'
  AND question_en = 'Describe what you usually do before starting a side project, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'While waiting at the airport, what do you usually do, and why?'
WHERE id = 'prompt-routine-1124'
  AND question_en = 'When it is while waiting at the airport, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What do you usually do after taking a short nap, and which part of that routine helps you the most?'
WHERE id = 'prompt-routine-1125'
  AND question_en = 'What do you usually do after taking a short nap, and what part of that routine helps you most?';

UPDATE prompts
SET question_en = 'What do you usually do during a break on campus, and why does that routine work well for you?'
WHERE id = 'prompt-routine-1126'
  AND question_en = 'Describe what you usually do during a break on campus, and explain why that routine works well for you.';

UPDATE prompts
SET question_en = 'Before recording a video for yourself or class, what do you usually do, and why?'
WHERE id = 'prompt-routine-1127'
  AND question_en = 'When it is before recording a video for yourself or class, what do you normally do, and why?';

UPDATE prompts
SET question_en = 'What is your favorite weekday breakfast, and why do you like it?'
WHERE id = 'prompt-preference-1101'
  AND question_en = 'What is your favorite weekday breakfast menu, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite summer fruit and explain why you like it so much.'
WHERE id = 'prompt-preference-1102'
  AND question_en = 'Tell me about your favorite summer fruit and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'Describe your favorite rainy-day drink and explain what you like most about it.'
WHERE id = 'prompt-preference-1103'
  AND question_en = 'Describe your favorite rainy-day drink and say what you like most about it.';

UPDATE prompts
SET question_en = 'What is your favorite phone case style, and why do you like it?'
WHERE id = 'prompt-preference-1104'
  AND question_en = 'What is your favorite phone case style, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite notebook type and explain why you like it so much.'
WHERE id = 'prompt-preference-1105'
  AND question_en = 'Tell me about your favorite notebook type and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'Describe your favorite place to read and explain what you like most about it.'
WHERE id = 'prompt-preference-1106'
  AND question_en = 'Describe your favorite place to read and say what you like most about it.';

UPDATE prompts
SET question_en = 'What is your favorite kind of soup, and why do you like it?'
WHERE id = 'prompt-preference-1107'
  AND question_en = 'What is your favorite kind of soup, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite type of bag and explain why you like it so much.'
WHERE id = 'prompt-preference-1108'
  AND question_en = 'Tell me about your favorite type of bag and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'Describe your favorite board game and explain what you like most about it.'
WHERE id = 'prompt-preference-1109'
  AND question_en = 'Describe your favorite board game and say what you like most about it.';

UPDATE prompts
SET question_en = 'What is your favorite way to study vocabulary, and why do you like it?'
WHERE id = 'prompt-preference-1110'
  AND question_en = 'What is your favorite way to study vocabulary, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite flower scent and explain why you like it so much.'
WHERE id = 'prompt-preference-1111'
  AND question_en = 'Tell me about your favorite flower scent and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'Describe your favorite seat on the bus and explain what you like most about it.'
WHERE id = 'prompt-preference-1112'
  AND question_en = 'Describe your favorite seat on the bus and say what you like most about it.';

UPDATE prompts
SET question_en = 'What is your favorite kind of weather for walking, and why do you like it?'
WHERE id = 'prompt-preference-1113'
  AND question_en = 'What is your favorite kind of weather for walking, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite type of sandwich and explain why you like it so much.'
WHERE id = 'prompt-preference-1114'
  AND question_en = 'Tell me about your favorite type of sandwich and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'Describe your favorite kitchen tool and explain what you like most about it.'
WHERE id = 'prompt-preference-1115'
  AND question_en = 'Describe your favorite kitchen tool and say what you like most about it.';

UPDATE prompts
SET question_en = 'What is your favorite kind of exercise class, and why do you like it?'
WHERE id = 'prompt-preference-1116'
  AND question_en = 'What is your favorite kind of exercise class, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite online creator and explain why you like it so much.'
WHERE id = 'prompt-preference-1117'
  AND question_en = 'Tell me about your favorite online creator and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'Describe your favorite snack for work or study breaks and explain what you like most about it.'
WHERE id = 'prompt-preference-1118'
  AND question_en = 'Describe your favorite snack for work or study breaks and say what you like most about it.';

UPDATE prompts
SET question_en = 'What is your favorite type of pen, and why do you like it?'
WHERE id = 'prompt-preference-1119'
  AND question_en = 'What is your favorite type of pen, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite bakery item and explain why you like it so much.'
WHERE id = 'prompt-preference-1120'
  AND question_en = 'Tell me about your favorite bakery item and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'Describe your favorite movie snack and explain what you like most about it.'
WHERE id = 'prompt-preference-1121'
  AND question_en = 'Describe your favorite movie snack and say what you like most about it.';

UPDATE prompts
SET question_en = 'What is your favorite travel souvenir, and why do you like it?'
WHERE id = 'prompt-preference-1122'
  AND question_en = 'What is your favorite travel souvenir, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite candle scent and explain why you like it so much.'
WHERE id = 'prompt-preference-1123'
  AND question_en = 'Tell me about your favorite candle scent and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'Describe your favorite way to organize photos and explain what you like most about it.'
WHERE id = 'prompt-preference-1124'
  AND question_en = 'Describe your favorite way to organize photos and say what you like most about it.';

UPDATE prompts
SET question_en = 'What is your favorite kind of tea, and why do you like it?'
WHERE id = 'prompt-preference-1125'
  AND question_en = 'What is your favorite kind of tea, and what makes it enjoyable for you?';

UPDATE prompts
SET question_en = 'Tell me about your favorite light jacket and explain why you like it so much.'
WHERE id = 'prompt-preference-1126'
  AND question_en = 'Tell me about your favorite light jacket and explain why you keep choosing it.';

UPDATE prompts
SET question_en = 'What is one health goal you want to reach this year, and how will you work toward it?'
WHERE id = 'prompt-goal-11'
  AND question_en = 'What is one health goal you want to reach this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one language goal you want to focus on this year, and how will you work toward it?'
WHERE id = 'prompt-goal-16'
  AND question_en = 'What is one language goal you want to work on this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one career skill you want to build this year, and how will you work toward it?'
WHERE id = 'prompt-goal-26'
  AND question_en = 'What is one career skill you want to build this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one reading habit you want to build this year, and how will you work toward it?'
WHERE id = 'prompt-goal-31'
  AND question_en = 'What is one reading habit you want to build this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one savings goal you want to reach this year, and how will you work toward it?'
WHERE id = 'prompt-goal-36'
  AND question_en = 'What is one savings goal you want to reach this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one fitness routine you want to keep this year, and how will you work toward it?'
WHERE id = 'prompt-goal-41'
  AND question_en = 'What is one fitness routine you want to keep this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one creative project you want to finish this year, and how will you work toward it?'
WHERE id = 'prompt-goal-46'
  AND question_en = 'What is one creative project you want to finish this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for improving your sleep schedule this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1101'
  AND question_en = 'What is one goal you have for improving your sleep schedule this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for organizing your digital files this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1104'
  AND question_en = 'What is one goal you have for organizing your digital files this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for practicing photography regularly this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1107'
  AND question_en = 'What is one goal you have for practicing photography regularly this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for building a better stretching habit this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1110'
  AND question_en = 'What is one goal you have for building a better stretching habit this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for making your mornings calmer this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1113'
  AND question_en = 'What is one goal you have for making your mornings calmer this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for reducing food waste at home this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1116'
  AND question_en = 'What is one goal you have for reducing food waste at home this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for building a weekend reset routine this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1119'
  AND question_en = 'What is one goal you have for building a weekend reset routine this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for remembering names more easily this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1122'
  AND question_en = 'What is one goal you have for remembering names more easily this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'What is one goal you have for making better use of small pockets of time this year, and how will you work toward it?'
WHERE id = 'prompt-goal-1125'
  AND question_en = 'What is one goal you have for making better use of small pockets of time this year, and how will you work on it?';

UPDATE prompts
SET question_en = 'Do you think open-plan offices are more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1102'
  AND question_en = 'Do you think open-plan offices are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of reusable packaging rules, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1103'
  AND question_en = 'How do you see the strengths and weaknesses of reusable packaging rules, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'Do you think online petitions are more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1105'
  AND question_en = 'Do you think online petitions are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of smart home devices, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1106'
  AND question_en = 'How do you see the strengths and weaknesses of smart home devices, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'Do you think cashless school cafeterias are more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1108'
  AND question_en = 'Do you think cashless school cafeterias are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of pet-friendly offices, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1109'
  AND question_en = 'How do you see the strengths and weaknesses of pet-friendly offices, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'Do you think digital textbooks are more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1111'
  AND question_en = 'Do you think digital textbooks are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of neighborhood security cameras, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1112'
  AND question_en = 'How do you see the strengths and weaknesses of neighborhood security cameras, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'Do you think AI customer service is more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1114'
  AND question_en = 'Do you think AI customer service are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of bicycle sharing systems, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1115'
  AND question_en = 'How do you see the strengths and weaknesses of bicycle sharing systems, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'Do you think four-day workweeks are more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1117'
  AND question_en = 'Do you think four-day workweeks are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of location sharing among friends, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1118'
  AND question_en = 'How do you see the strengths and weaknesses of location sharing among friends, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'Do you think live-stream shopping is more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1120'
  AND question_en = 'Do you think live-stream shopping are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of reusable cup deposit programs, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1121'
  AND question_en = 'How do you see the strengths and weaknesses of reusable cup deposit programs, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'Do you think meal kit services are more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1123'
  AND question_en = 'Do you think meal kit services are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of personal data rewards programs, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1124'
  AND question_en = 'How do you see the strengths and weaknesses of personal data rewards programs, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'Do you think office hot-desking is more helpful or harmful overall? Explain both sides and give your opinion.'
WHERE id = 'prompt-balance-1126'
  AND question_en = 'Do you think office hot-desking are mostly helpful or mostly harmful? Explain both sides and your opinion.';

UPDATE prompts
SET question_en = 'What do you see as the strengths and weaknesses of second-screen viewing habits, and which side seems stronger to you?'
WHERE id = 'prompt-balance-1127'
  AND question_en = 'How do you see the strengths and weaknesses of second-screen viewing habits, and which side seems stronger to you?';

UPDATE prompts
SET question_en = 'What social responsibilities should successful companies have in modern society?'
WHERE id = 'prompt-c-2'
  AND question_en = 'What kind of social responsibility should successful companies have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should public transportation in big cities have in modern society?'
WHERE id = 'prompt-opinion-06'
  AND question_en = 'What responsibility should public transportation in big cities have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should schools that teach financial skills have in modern society?'
WHERE id = 'prompt-opinion-11'
  AND question_en = 'What responsibility should schools that teach financial skills have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should local volunteering have in modern society?'
WHERE id = 'prompt-opinion-16'
  AND question_en = 'What responsibility should local volunteering have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should social media platforms have in modern society?'
WHERE id = 'prompt-opinion-21'
  AND question_en = 'What responsibility should social media platforms have in modern society?';

UPDATE prompts
SET question_en = 'What role should public libraries play in modern society?'
WHERE id = 'prompt-opinion-26'
  AND question_en = 'What role should public libraries have in modern society?';

UPDATE prompts
SET question_en = 'What role should school uniforms in public schools play in modern society?'
WHERE id = 'prompt-opinion-31'
  AND question_en = 'What role should school uniforms in public schools have in modern society?';

UPDATE prompts
SET question_en = 'What role should recycling programs play in modern society?'
WHERE id = 'prompt-opinion-36'
  AND question_en = 'What role should recycling programs have in modern society?';

UPDATE prompts
SET question_en = 'What role should part-time jobs for teenagers play in modern society?'
WHERE id = 'prompt-opinion-41'
  AND question_en = 'What role should part-time jobs for teenagers have in modern society?';

UPDATE prompts
SET question_en = 'What role should community arts programs play in modern society?'
WHERE id = 'prompt-opinion-46'
  AND question_en = 'What role should community arts programs have in modern society?';

UPDATE prompts
SET question_en = 'What role should neighborhood parks play in modern society?'
WHERE id = 'prompt-opinion-1101'
  AND question_en = 'What role should neighborhood parks have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should public museums have in the community today?'
WHERE id = 'prompt-opinion-1102'
  AND question_en = 'What responsibility should public museums have in the community today?';

UPDATE prompts
SET question_en = 'What role should universities play in modern society?'
WHERE id = 'prompt-opinion-1104'
  AND question_en = 'What role should universities have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should local news outlets have in the community today?'
WHERE id = 'prompt-opinion-1105'
  AND question_en = 'What responsibility should local news outlets have in the community today?';

UPDATE prompts
SET question_en = 'What role should sports clubs for teenagers play in modern society?'
WHERE id = 'prompt-opinion-1107'
  AND question_en = 'What role should sports clubs for teenagers have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should public health campaigns have in the community today?'
WHERE id = 'prompt-opinion-1108'
  AND question_en = 'What responsibility should public health campaigns have in the community today?';

UPDATE prompts
SET question_en = 'What role should animal shelters play in modern society?'
WHERE id = 'prompt-opinion-1110'
  AND question_en = 'What role should animal shelters have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should public broadcasters have in the community today?'
WHERE id = 'prompt-opinion-1111'
  AND question_en = 'What responsibility should public broadcasters have in the community today?';

UPDATE prompts
SET question_en = 'What role should local farmers'' markets play in modern society?'
WHERE id = 'prompt-opinion-1113'
  AND question_en = 'What role should local farmers'' markets have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should after-school programs have in the community today?'
WHERE id = 'prompt-opinion-1114'
  AND question_en = 'What responsibility should after-school programs have in the community today?';

UPDATE prompts
SET question_en = 'What role should city bike systems play in modern society?'
WHERE id = 'prompt-opinion-1116'
  AND question_en = 'What role should city bike systems have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should employers offering internships have in the community today?'
WHERE id = 'prompt-opinion-1117'
  AND question_en = 'What responsibility should employers offering internships have in the community today?';

UPDATE prompts
SET question_en = 'What role should schools teaching online safety play in modern society?'
WHERE id = 'prompt-opinion-1119'
  AND question_en = 'What role should schools teaching online safety have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should local governments running heat shelters have in the community today?'
WHERE id = 'prompt-opinion-1120'
  AND question_en = 'What responsibility should local governments running heat shelters have in the community today?';

UPDATE prompts
SET question_en = 'What role should volunteer matching platforms play in modern society?'
WHERE id = 'prompt-opinion-1122'
  AND question_en = 'What role should volunteer matching platforms have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should apartment recycling rooms have in the community today?'
WHERE id = 'prompt-opinion-1123'
  AND question_en = 'What responsibility should apartment recycling rooms have in the community today?';

UPDATE prompts
SET question_en = 'What role should senior centers play in modern society?'
WHERE id = 'prompt-opinion-1125'
  AND question_en = 'What role should senior centers have in modern society?';

UPDATE prompts
SET question_en = 'What responsibilities should public swimming pools have in the community today?'
WHERE id = 'prompt-opinion-1126'
  AND question_en = 'What responsibility should public swimming pools have in the community today?';

UPDATE prompts
SET question_en = 'How has your view of social media changed over time, and why?'
WHERE id = 'prompt-reflection-11'
  AND question_en = 'Describe how your view of social media has changed over time and explain why.';

UPDATE prompts
SET question_en = 'How has your view of competition changed over time, and why?'
WHERE id = 'prompt-reflection-1101'
  AND question_en = 'Describe how your view of competition has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of living alone has changed over time and explain why.'
WHERE id = 'prompt-reflection-1103'
  AND question_en = 'Tell me about a way your opinion of living alone has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'How has your view of networking changed over time, and why?'
WHERE id = 'prompt-reflection-1104'
  AND question_en = 'Describe how your view of networking has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of asking for help has changed over time and explain why.'
WHERE id = 'prompt-reflection-1106'
  AND question_en = 'Tell me about a way your opinion of asking for help has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'How has your view of productivity changed over time, and why?'
WHERE id = 'prompt-reflection-1107'
  AND question_en = 'Describe how your view of productivity has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of fashion has changed over time and explain why.'
WHERE id = 'prompt-reflection-1109'
  AND question_en = 'Tell me about a way your opinion of fashion has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'How has your view of time spent alone changed over time, and why?'
WHERE id = 'prompt-reflection-1110'
  AND question_en = 'Describe how your view of time spent alone has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of online classes has changed over time and explain why.'
WHERE id = 'prompt-reflection-1112'
  AND question_en = 'Tell me about a way your opinion of online classes has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'How has your view of keeping a diary changed over time, and why?'
WHERE id = 'prompt-reflection-1113'
  AND question_en = 'Describe how your view of keeping a diary has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of routines has changed over time and explain why.'
WHERE id = 'prompt-reflection-1115'
  AND question_en = 'Tell me about a way your opinion of routines has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'How has your view of mistakes changed over time, and why?'
WHERE id = 'prompt-reflection-1116'
  AND question_en = 'Describe how your view of mistakes has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of spending weekends has changed over time and explain why.'
WHERE id = 'prompt-reflection-1118'
  AND question_en = 'Tell me about a way your opinion of spending weekends has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'How has your view of owning fewer things changed over time, and why?'
WHERE id = 'prompt-reflection-1119'
  AND question_en = 'Describe how your view of owning fewer things has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of teamwork has changed over time and explain why.'
WHERE id = 'prompt-reflection-1121'
  AND question_en = 'Tell me about a way your opinion of teamwork has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'How has your view of privacy changed over time, and why?'
WHERE id = 'prompt-reflection-1122'
  AND question_en = 'Describe how your view of privacy has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of cooking at home has changed over time and explain why.'
WHERE id = 'prompt-reflection-1124'
  AND question_en = 'Tell me about a way your opinion of cooking at home has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'How has your view of public speaking changed over time, and why?'
WHERE id = 'prompt-reflection-1125'
  AND question_en = 'Describe how your view of public speaking has changed over time and explain why.';

UPDATE prompts
SET question_en = 'Tell me how your opinion of planning ahead has changed over time and explain why.'
WHERE id = 'prompt-reflection-1127'
  AND question_en = 'Tell me about a way your opinion of planning ahead has changed over time and why it changed.';

UPDATE prompts
SET question_en = 'Tell me about a small desk item you use every day and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1102'
  AND question_en = 'Tell me about a small desk item you use every day and say why it feels meaningful to you.';

UPDATE prompts
SET question_en = 'Describe a bus route you know well that stands out to you and explain why it has stayed in your memory.'
WHERE id = 'prompt-general-1103'
  AND question_en = 'Describe a bus route you know well that stands out to you and explain why you remember it well.';

UPDATE prompts
SET question_en = 'Tell me about a corner of your room you like and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1105'
  AND question_en = 'Tell me about a corner of your room you like and say why it feels meaningful to you.';

UPDATE prompts
SET question_en = 'Describe a local bridge or walkway you like crossing that stands out to you and explain why it has stayed in your memory.'
WHERE id = 'prompt-general-1106'
  AND question_en = 'Describe a local bridge or walkway you like crossing that stands out to you and explain why you remember it well.';

UPDATE prompts
SET question_en = 'Tell me about a meal you learned to cook yourself and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1108'
  AND question_en = 'Tell me about a meal you learned to cook yourself and say why it feels meaningful to you.';

UPDATE prompts
SET question_en = 'Describe a cafe you revisit often that stands out to you and explain why it has stayed in your memory.'
WHERE id = 'prompt-general-1109'
  AND question_en = 'Describe a cafe you revisit often that stands out to you and explain why you remember it well.';

UPDATE prompts
SET question_en = 'Tell me about a phone feature you rely on and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1111'
  AND question_en = 'Tell me about a phone feature you rely on and say why it feels meaningful to you.';

UPDATE prompts
SET question_en = 'Describe a notebook you carry around that stands out to you and explain why it has stayed in your memory.'
WHERE id = 'prompt-general-1112'
  AND question_en = 'Describe a notebook you carry around that stands out to you and explain why you remember it well.';

UPDATE prompts
SET question_en = 'Tell me about a volunteer event you joined and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1114'
  AND question_en = 'Tell me about a volunteer event you joined and say why it feels meaningful to you.';

UPDATE prompts
SET question_en = 'Describe a topic you enjoy talking about that stands out to you and explain why it has stayed in your memory.'
WHERE id = 'prompt-general-1115'
  AND question_en = 'Describe a topic you enjoy talking about that stands out to you and explain why you remember it well.';

UPDATE prompts
SET question_en = 'Tell me about a market stall you like visiting and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1117'
  AND question_en = 'Tell me about a market stall you like visiting and say why it feels meaningful to you.';

UPDATE prompts
SET question_en = 'Describe a rainy-day sound you like that stands out to you and explain why it has stayed in your memory.'
WHERE id = 'prompt-general-1118'
  AND question_en = 'Describe a rainy-day sound you like that stands out to you and explain why you remember it well.';

UPDATE prompts
SET question_en = 'Tell me about a community class you found useful and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1120'
  AND question_en = 'Tell me about a community class you found useful and say why it feels meaningful to you.';

UPDATE prompts
SET question_en = 'Describe a plant you take care of that stands out to you and explain why it has stayed in your memory.'
WHERE id = 'prompt-general-1121'
  AND question_en = 'Describe a plant you take care of that stands out to you and explain why you remember it well.';

UPDATE prompts
SET question_en = 'Tell me about a nearby river path or street you know well and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1123'
  AND question_en = 'Tell me about a nearby river path or street you know well and say why it feels meaningful to you.';

UPDATE prompts
SET question_en = 'Describe a recipe from your home that stands out to you and explain why it has stayed in your memory.'
WHERE id = 'prompt-general-1124'
  AND question_en = 'Describe a recipe from your home that stands out to you and explain why you remember it well.';

UPDATE prompts
SET question_en = 'Tell me about a shortcut in your neighborhood and explain why it feels meaningful to you.'
WHERE id = 'prompt-general-1126'
  AND question_en = 'Tell me about a shortcut in your neighborhood and say why it feels meaningful to you.';
