-- Reclassify active action-like VOCAB_WORD items into VOCAB_PHRASE.
-- Generated by scripts/generate_active_hint_phrase_reclass_042.py

-- prompt-a-1: What do you usually do after dinner?
UPDATE prompt_hint_items
SET hint_id = 'hint-a-1-3',
    item_type = 'PHRASE',
    display_order = 6
WHERE id = 'hint-a-1-2-item-2'
  AND hint_id = 'hint-a-1-2'
  AND item_type = 'WORD'
  AND content = 'wash the dishes';

UPDATE prompt_hint_items
SET hint_id = 'hint-a-1-3',
    item_type = 'PHRASE',
    display_order = 7
WHERE id = 'hint-a-1-2-item-3'
  AND hint_id = 'hint-a-1-2'
  AND item_type = 'WORD'
  AND content = 'watch videos';

UPDATE prompt_hint_items
SET hint_id = 'hint-a-1-3',
    item_type = 'PHRASE',
    display_order = 8
WHERE id = 'hint-a-1-2-item-4'
  AND hint_id = 'hint-a-1-2'
  AND item_type = 'WORD'
  AND content = 'take a walk';

UPDATE prompt_hint_items
SET hint_id = 'hint-a-1-3',
    item_type = 'PHRASE',
    display_order = 9
WHERE id = 'hint-a-1-2-item-5'
  AND hint_id = 'hint-a-1-2'
  AND item_type = 'WORD'
  AND content = 'get ready for bed';

UPDATE prompt_hint_items
SET display_order = 1
WHERE id = 'hint-a-1-2-item-1'
  AND hint_id = 'hint-a-1-2';

-- prompt-a-3: How do you usually spend your weekend?
UPDATE prompt_hint_items
SET hint_id = 'hint-a-3-3',
    item_type = 'PHRASE',
    display_order = 6
WHERE id = 'hint-a-3-2-item-2'
  AND hint_id = 'hint-a-3-2'
  AND item_type = 'WORD'
  AND content = 'meet friends';

UPDATE prompt_hint_items
SET hint_id = 'hint-a-3-3',
    item_type = 'PHRASE',
    display_order = 7
WHERE id = 'hint-a-3-2-item-5'
  AND hint_id = 'hint-a-3-2'
  AND item_type = 'WORD'
  AND content = 'go out';

UPDATE prompt_hint_items
SET display_order = 1
WHERE id = 'hint-a-3-2-item-1'
  AND hint_id = 'hint-a-3-2';

UPDATE prompt_hint_items
SET display_order = 2
WHERE id = 'hint-a-3-2-item-3'
  AND hint_id = 'hint-a-3-2';

UPDATE prompt_hint_items
SET display_order = 3
WHERE id = 'hint-a-3-2-item-4'
  AND hint_id = 'hint-a-3-2';

-- prompt-a-4: What do you usually do after work, and why do you enjoy it?
UPDATE prompt_hint_items
SET hint_id = 'hint-a-4-3',
    item_type = 'PHRASE',
    display_order = 6
WHERE id = 'hint-a-4-2-item-2'
  AND hint_id = 'hint-a-4-2'
  AND item_type = 'WORD'
  AND content = 'grab dinner';

UPDATE prompt_hint_items
SET hint_id = 'hint-a-4-3',
    item_type = 'PHRASE',
    display_order = 7
WHERE id = 'hint-a-4-2-item-3'
  AND hint_id = 'hint-a-4-2'
  AND item_type = 'WORD'
  AND content = 'work out';

UPDATE prompt_hint_items
SET display_order = 1
WHERE id = 'hint-a-4-2-item-1'
  AND hint_id = 'hint-a-4-2';

UPDATE prompt_hint_items
SET display_order = 2
WHERE id = 'hint-a-4-2-item-4'
  AND hint_id = 'hint-a-4-2';

UPDATE prompt_hint_items
SET display_order = 3
WHERE id = 'hint-a-4-2-item-5'
  AND hint_id = 'hint-a-4-2';

-- prompt-routine-01: How do you usually spend your weekday mornings?
UPDATE prompt_hint_items
SET hint_id = 'hint-rtn-01-3',
    item_type = 'PHRASE',
    display_order = 5
WHERE id = 'hint-rtn-01-2-item-1'
  AND hint_id = 'hint-rtn-01-2'
  AND item_type = 'WORD'
  AND content = 'wake up';

UPDATE prompt_hint_items
SET hint_id = 'hint-rtn-01-3',
    item_type = 'PHRASE',
    display_order = 6
WHERE id = 'hint-rtn-01-2-item-2'
  AND hint_id = 'hint-rtn-01-2'
  AND item_type = 'WORD'
  AND content = 'get ready';

UPDATE prompt_hint_items
SET display_order = 1
WHERE id = 'hint-rtn-01-2-item-3'
  AND hint_id = 'hint-rtn-01-2';

UPDATE prompt_hint_items
SET display_order = 2
WHERE id = 'hint-rtn-01-2-item-4'
  AND hint_id = 'hint-rtn-01-2';

UPDATE prompt_hint_items
SET display_order = 3
WHERE id = 'hint-rtn-01-2-item-5'
  AND hint_id = 'hint-rtn-01-2';

UPDATE prompt_hint_items
SET display_order = 4
WHERE id = 'hint-rtn-01-2-item-6'
  AND hint_id = 'hint-rtn-01-2';

UPDATE prompt_hint_items
SET display_order = 5
WHERE id = 'hint-rtn-01-2-item-7'
  AND hint_id = 'hint-rtn-01-2';

UPDATE prompt_hint_items
SET display_order = 6
WHERE id = 'hint-rtn-01-2-item-8'
  AND hint_id = 'hint-rtn-01-2';

UPDATE prompt_hint_items
SET display_order = 7
WHERE id = 'hint-rtn-01-2-item-9'
  AND hint_id = 'hint-rtn-01-2';

UPDATE prompt_hint_items
SET display_order = 8
WHERE id = 'hint-rtn-01-2-item-10'
  AND hint_id = 'hint-rtn-01-2';

UPDATE prompt_hint_items
SET display_order = 9
WHERE id = 'hint-rtn-01-2-item-11'
  AND hint_id = 'hint-rtn-01-2';

-- prompt-routine-11: How do you usually spend your Sunday afternoons?
UPDATE prompt_hint_items
SET hint_id = 'hint-rtn-11-3',
    item_type = 'PHRASE',
    display_order = 5
WHERE id = 'hint-rtn-11-2-item-4'
  AND hint_id = 'hint-rtn-11-2'
  AND item_type = 'WORD'
  AND content = 'meet friends';

UPDATE prompt_hint_items
SET display_order = 1
WHERE id = 'hint-rtn-11-2-item-1'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 2
WHERE id = 'hint-rtn-11-2-item-2'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 3
WHERE id = 'hint-rtn-11-2-item-3'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 4
WHERE id = 'hint-rtn-11-2-item-5'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 5
WHERE id = 'hint-rtn-11-2-item-6'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 6
WHERE id = 'hint-rtn-11-2-item-7'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 7
WHERE id = 'hint-rtn-11-2-item-8'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 8
WHERE id = 'hint-rtn-11-2-item-9'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 9
WHERE id = 'hint-rtn-11-2-item-10'
  AND hint_id = 'hint-rtn-11-2';

UPDATE prompt_hint_items
SET display_order = 10
WHERE id = 'hint-rtn-11-2-item-11'
  AND hint_id = 'hint-rtn-11-2';

-- prompt-routine-16: How do you usually spend your free time at home?
UPDATE prompt_hint_items
SET hint_id = 'hint-rtn-16-3',
    item_type = 'PHRASE',
    display_order = 5
WHERE id = 'hint-rtn-16-2-item-1'
  AND hint_id = 'hint-rtn-16-2'
  AND item_type = 'WORD'
  AND content = 'stay home';

UPDATE prompt_hint_items
SET hint_id = 'hint-rtn-16-3',
    item_type = 'PHRASE',
    display_order = 6
WHERE id = 'hint-rtn-16-2-item-2'
  AND hint_id = 'hint-rtn-16-2'
  AND item_type = 'WORD'
  AND content = 'watch shows';

UPDATE prompt_hint_items
SET display_order = 1
WHERE id = 'hint-rtn-16-2-item-3'
  AND hint_id = 'hint-rtn-16-2';

UPDATE prompt_hint_items
SET display_order = 2
WHERE id = 'hint-rtn-16-2-item-4'
  AND hint_id = 'hint-rtn-16-2';

UPDATE prompt_hint_items
SET display_order = 3
WHERE id = 'hint-rtn-16-2-item-5'
  AND hint_id = 'hint-rtn-16-2';

UPDATE prompt_hint_items
SET display_order = 4
WHERE id = 'hint-rtn-16-2-item-6'
  AND hint_id = 'hint-rtn-16-2';

UPDATE prompt_hint_items
SET display_order = 5
WHERE id = 'hint-rtn-16-2-item-7'
  AND hint_id = 'hint-rtn-16-2';

UPDATE prompt_hint_items
SET display_order = 6
WHERE id = 'hint-rtn-16-2-item-8'
  AND hint_id = 'hint-rtn-16-2';

UPDATE prompt_hint_items
SET display_order = 7
WHERE id = 'hint-rtn-16-2-item-9'
  AND hint_id = 'hint-rtn-16-2';

UPDATE prompt_hint_items
SET display_order = 8
WHERE id = 'hint-rtn-16-2-item-10'
  AND hint_id = 'hint-rtn-16-2';

UPDATE prompt_hint_items
SET display_order = 9
WHERE id = 'hint-rtn-16-2-item-11'
  AND hint_id = 'hint-rtn-16-2';

-- prompt-routine-21: How do you usually start your Saturdays?
UPDATE prompt_hint_items
SET hint_id = 'hint-rtn-21-3',
    item_type = 'PHRASE',
    display_order = 5
WHERE id = 'hint-rtn-21-2-item-1'
  AND hint_id = 'hint-rtn-21-2'
  AND item_type = 'WORD'
  AND content = 'sleep in';

UPDATE prompt_hint_items
SET hint_id = 'hint-rtn-21-3',
    item_type = 'PHRASE',
    display_order = 6
WHERE id = 'hint-rtn-21-2-item-4'
  AND hint_id = 'hint-rtn-21-2'
  AND item_type = 'WORD'
  AND content = 'tidy up';

UPDATE prompt_hint_items
SET display_order = 1
WHERE id = 'hint-rtn-21-2-item-2'
  AND hint_id = 'hint-rtn-21-2';

UPDATE prompt_hint_items
SET display_order = 2
WHERE id = 'hint-rtn-21-2-item-3'
  AND hint_id = 'hint-rtn-21-2';

UPDATE prompt_hint_items
SET display_order = 3
WHERE id = 'hint-rtn-21-2-item-5'
  AND hint_id = 'hint-rtn-21-2';

UPDATE prompt_hint_items
SET display_order = 4
WHERE id = 'hint-rtn-21-2-item-6'
  AND hint_id = 'hint-rtn-21-2';

UPDATE prompt_hint_items
SET display_order = 5
WHERE id = 'hint-rtn-21-2-item-7'
  AND hint_id = 'hint-rtn-21-2';

UPDATE prompt_hint_items
SET display_order = 6
WHERE id = 'hint-rtn-21-2-item-8'
  AND hint_id = 'hint-rtn-21-2';

UPDATE prompt_hint_items
SET display_order = 7
WHERE id = 'hint-rtn-21-2-item-9'
  AND hint_id = 'hint-rtn-21-2';

UPDATE prompt_hint_items
SET display_order = 8
WHERE id = 'hint-rtn-21-2-item-10'
  AND hint_id = 'hint-rtn-21-2';

UPDATE prompt_hint_items
SET display_order = 9
WHERE id = 'hint-rtn-21-2-item-11'
  AND hint_id = 'hint-rtn-21-2';
