CREATE TABLE IF NOT EXISTS feedback_timing_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    trace_id VARCHAR(64) NOT NULL,
    feedback_type VARCHAR(32) NOT NULL,
    phase_scope VARCHAR(32) NOT NULL,
    phase VARCHAR(80) NOT NULL,
    user_id BIGINT NULL,
    guest_id VARCHAR(64) NULL,
    prompt_id VARCHAR(64) NULL,
    diary_entry_id VARCHAR(64) NULL,
    session_id VARCHAR(64) NULL,
    answer_attempt_id BIGINT NULL,
    diary_attempt_id BIGINT NULL,
    attempt_no INT NULL,
    provider VARCHAR(32) NULL,
    model VARCHAR(128) NULL,
    reasoning_effort VARCHAR(32) NULL,
    thinking_budget INT NULL,
    success BIT(1) NULL,
    status_code INT NULL,
    exception_class VARCHAR(255) NULL,
    elapsed_ms BIGINT NOT NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_feedback_timing_trace (trace_id),
    KEY idx_feedback_timing_type_created (feedback_type, created_at),
    KEY idx_feedback_timing_phase_created (phase, created_at),
    KEY idx_feedback_timing_prompt_created (prompt_id, created_at),
    KEY idx_feedback_timing_diary_created (diary_entry_id, created_at),
    KEY idx_feedback_timing_provider_model_created (provider, model, created_at)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
