-- Re-align experience-style prompt starters with the exact prompt topic.
-- Generated by scripts/generate_experience_prompt_alignment_063.py.

UPDATE prompts
SET question_en = 'Think about a bottle shape that feels comfortable in your hand. When would you choose that bottle, and how would it help you in that moment?',
    question_ko = '손에 잡기 편한 물병 모양을 떠올려 보세요. 언제 그 물병을 고르고, 그 순간에 어떻게 도움이 되나요?',
    tip = '물병의 모양 자체보다 실제로 들고 다니는 상황과 편한 이유를 말해 보세요.'
WHERE id = 'prompt-preference-2514';

UPDATE prompt_hint_items
SET content = 'When I need a quick meal at home, I usually choose ... because ...',
    example_en = 'When I need a quick meal at home, I usually choose fried rice because it is easy.'
WHERE id = 'hint-a-2-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I watch a movie, I usually choose ... because ...',
    example_en = 'When I watch a movie, I usually choose comedy because it helps me relax.'
WHERE id = 'hint-pref-06-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a break, I like to relax at ... because ...',
    example_en = 'When I need a break, I like to relax at a quiet cafe because it feels peaceful.'
WHERE id = 'hint-pref-11-1-item-1';

UPDATE prompt_hint_items
SET content = 'During ..., I like to ... because ...',
    example_en = 'During spring, I like to take walks because the weather feels fresh.'
WHERE id = 'hint-pref-16-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I ..., I like to listen to ... because ...',
    example_en = 'When I study, I like to listen to calm music because it helps me focus.'
WHERE id = 'hint-pref-21-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go to a cafe, I usually order ... because ...',
    example_en = 'When I go to a cafe, I usually order iced tea because it feels refreshing.'
WHERE id = 'hint-pref-26-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I read for fun, I usually choose ... because ...',
    example_en = 'When I read for fun, I usually choose mystery books because they keep me curious.'
WHERE id = 'hint-pref-31-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want dessert, I usually choose ... because ...',
    example_en = 'When I want dessert, I usually choose cheesecake because it feels special.'
WHERE id = 'hint-pref-36-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want to exercise, I usually ... because ...',
    example_en = 'When I want to exercise, I usually take a walk because it is simple.'
WHERE id = 'hint-pref-41-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need to focus, I study at ... because ...',
    example_en = 'When I need to focus, I study at my desk because it is quiet.'
WHERE id = 'hint-pref-46-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a weekday breakfast because ...',
    example_en = 'When I want something to eat, I choose a weekday breakfast because it fits that moment.'
WHERE id = 'hint-preference-1101-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a summer fruit because ...',
    example_en = 'When I want something to eat, I choose a summer fruit because it fits that moment.'
WHERE id = 'hint-preference-1102-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a rainy-day drink because ...',
    example_en = 'When I need something to drink, I choose a rainy-day drink because it feels refreshing.'
WHERE id = 'hint-preference-1103-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a phone case style because ...',
    example_en = 'When I use my phone or an app, I choose a phone case style because it feels easy to use.'
WHERE id = 'hint-preference-1104-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a notebook type because ...',
    example_en = 'When I study or work, I use a notebook type because it helps me stay organized.'
WHERE id = 'hint-preference-1105-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a place to read because ...',
    example_en = 'When I need a short break, I choose a place to read because it feels comfortable.'
WHERE id = 'hint-preference-1106-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose soup because ...',
    example_en = 'When I want something to eat, I choose soup because it fits that moment.'
WHERE id = 'hint-preference-1107-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a bag because ...',
    example_en = 'When I go out, I carry a bag because it makes my day easier.'
WHERE id = 'hint-preference-1108-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a board game because ...',
    example_en = 'When I take a break, I choose a board game because it helps me relax.'
WHERE id = 'hint-preference-1109-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study vocabulary, I use ... because ...',
    example_en = 'When I study vocabulary, I use example sentences because they help me remember words.'
WHERE id = 'hint-preference-1110-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a flower scent because ...',
    example_en = 'When I take care of myself, I use a flower scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-1111-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a seat on the bus because ...',
    example_en = 'When I need a short break, I choose a seat on the bus because it feels comfortable.'
WHERE id = 'hint-preference-1112-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I walk outside, I like ... weather because ...',
    example_en = 'When I walk outside, I like cool weather because it feels comfortable.'
WHERE id = 'hint-preference-1113-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a sandwich because ...',
    example_en = 'When I want something to eat, I choose a sandwich because it fits that moment.'
WHERE id = 'hint-preference-1114-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a kitchen tool because ...',
    example_en = 'When I cook or eat at home, I use a kitchen tool because it is convenient.'
WHERE id = 'hint-preference-1115-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I join an exercise class, I choose ... because ...',
    example_en = 'When I join an exercise class, I choose yoga because it helps me keep going.'
WHERE id = 'hint-preference-1116-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a online creator because ...',
    example_en = 'When I use my phone or an app, I choose a online creator because it feels easy to use.'
WHERE id = 'hint-preference-1117-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a snack for work or study breaks because ...',
    example_en = 'When I want something to eat, I choose a snack for work or study breaks because it fits that moment.'
WHERE id = 'hint-preference-1118-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a pen because ...',
    example_en = 'When I study or work, I use a pen because it helps me stay organized.'
WHERE id = 'hint-preference-1119-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a bakery item because ...',
    example_en = 'When I want something to eat, I choose a bakery item because it fits that moment.'
WHERE id = 'hint-preference-1120-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a movie snack because ...',
    example_en = 'When I want something to eat, I choose a movie snack because it fits that moment.'
WHERE id = 'hint-preference-1121-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a travel souvenir because ...',
    example_en = 'When I need it, I choose a travel souvenir because it helps me.'
WHERE id = 'hint-preference-1122-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a candle scent because ...',
    example_en = 'When I take care of myself, I use a candle scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-1123-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a way to organize photos because ...',
    example_en = 'When I need it, I choose a way to organize photos because it helps me.'
WHERE id = 'hint-preference-1124-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose tea because ...',
    example_en = 'When I need something to drink, I choose tea because it feels refreshing.'
WHERE id = 'hint-preference-1125-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a light jacket because ...',
    example_en = 'When I get dressed, I choose a light jacket because it feels comfortable.'
WHERE id = 'hint-preference-1126-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a bread for breakfast because ...',
    example_en = 'When I want something to eat, I choose a bread for breakfast because it fits that moment.'
WHERE id = 'hint-preference-2201-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose fried eggs because ...',
    example_en = 'When I want something to eat, I choose fried eggs because it fits that moment.'
WHERE id = 'hint-preference-2202-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a fruit because ...',
    example_en = 'When I want something to eat, I choose a fruit because it fits that moment.'
WHERE id = 'hint-preference-2203-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a yogurt topping because ...',
    example_en = 'When I want something to eat, I choose a yogurt topping because it fits that moment.'
WHERE id = 'hint-preference-2204-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a cereal because ...',
    example_en = 'When I want something to eat, I choose a cereal because it fits that moment.'
WHERE id = 'hint-preference-2205-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a jam flavor because ...',
    example_en = 'When I want something to eat, I choose a jam flavor because it fits that moment.'
WHERE id = 'hint-preference-2206-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a toast topping because ...',
    example_en = 'When I want something to eat, I choose a toast topping because it fits that moment.'
WHERE id = 'hint-preference-2207-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a simple noodle dish because ...',
    example_en = 'When I want something to eat, I choose a simple noodle dish because it fits that moment.'
WHERE id = 'hint-preference-2208-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a side dish because ...',
    example_en = 'When I want something to eat, I choose a side dish because it fits that moment.'
WHERE id = 'hint-preference-2209-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a simple meal because ...',
    example_en = 'When I want something to eat, I choose a simple meal because it fits that moment.'
WHERE id = 'hint-preference-2210-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a snack because ...',
    example_en = 'When I want something to eat, I choose a snack because it fits that moment.'
WHERE id = 'hint-preference-2211-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a food because ...',
    example_en = 'When I want something to eat, I choose a food because it fits that moment.'
WHERE id = 'hint-preference-2212-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a rice bowl topping because ...',
    example_en = 'When I cook or eat at home, I use a rice bowl topping because it is convenient.'
WHERE id = 'hint-preference-2213-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a porridge for a quiet morning because ...',
    example_en = 'When I need it, I choose a porridge for a quiet morning because it helps me.'
WHERE id = 'hint-preference-2214-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a quick meal for a late morning because ...',
    example_en = 'When I want something to eat, I choose a quick meal for a late morning because it fits that moment.'
WHERE id = 'hint-preference-2215-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a cookie flavor because ...',
    example_en = 'When I want something to eat, I choose a cookie flavor because it fits that moment.'
WHERE id = 'hint-preference-2216-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a chip flavor because ...',
    example_en = 'When I want something to eat, I choose a chip flavor because it fits that moment.'
WHERE id = 'hint-preference-2217-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a ice cream flavor because ...',
    example_en = 'When I want something to eat, I choose a ice cream flavor because it fits that moment.'
WHERE id = 'hint-preference-2218-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a chocolate bar because ...',
    example_en = 'When I want something to eat, I choose a chocolate bar because it fits that moment.'
WHERE id = 'hint-preference-2219-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a candy flavor because ...',
    example_en = 'When I want something to eat, I choose a candy flavor because it fits that moment.'
WHERE id = 'hint-preference-2220-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a snack from a convenience store because ...',
    example_en = 'When I want something to eat, I choose a snack from a convenience store because it fits that moment.'
WHERE id = 'hint-preference-2221-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a cracker because ...',
    example_en = 'When I want something to eat, I choose a cracker because it fits that moment.'
WHERE id = 'hint-preference-2222-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a popcorn flavor because ...',
    example_en = 'When I want something to eat, I choose a popcorn flavor because it fits that moment.'
WHERE id = 'hint-preference-2223-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a sweet bread because ...',
    example_en = 'When I want something to eat, I choose a sweet bread because it fits that moment.'
WHERE id = 'hint-preference-2224-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a yogurt drink flavor because ...',
    example_en = 'When I need something to drink, I choose a yogurt drink flavor because it feels refreshing.'
WHERE id = 'hint-preference-2225-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a fruit candy because ...',
    example_en = 'When I want something to eat, I choose a fruit candy because it fits that moment.'
WHERE id = 'hint-preference-2226-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a late-night snack because ...',
    example_en = 'When I want something to eat, I choose a late-night snack because it fits that moment.'
WHERE id = 'hint-preference-2227-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a salty snack because ...',
    example_en = 'When I want something to eat, I choose a salty snack because it fits that moment.'
WHERE id = 'hint-preference-2228-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a snack with a soft texture because ...',
    example_en = 'When I want something to eat, I choose a snack with a soft texture because it fits that moment.'
WHERE id = 'hint-preference-2229-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a small treat after a long day because ...',
    example_en = 'When I need it, I choose a small treat after a long day because it helps me.'
WHERE id = 'hint-preference-2230-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a pencil because ...',
    example_en = 'When I study or work, I use a pencil because it helps me stay organized.'
WHERE id = 'hint-preference-2231-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use an eraser because ...',
    example_en = 'When I study or work, I use an eraser because it helps me stay organized.'
WHERE id = 'hint-preference-2232-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a highlighter color because ...',
    example_en = 'When I study or work, I use a highlighter color because it helps me stay organized.'
WHERE id = 'hint-preference-2233-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a sticky note shape because ...',
    example_en = 'When I study or work, I use a sticky note shape because it helps me stay organized.'
WHERE id = 'hint-preference-2234-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a planner layout because ...',
    example_en = 'When I study or work, I use a planner layout because it helps me stay organized.'
WHERE id = 'hint-preference-2235-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a bookmark style because ...',
    example_en = 'When I study or work, I use a bookmark style because it helps me stay organized.'
WHERE id = 'hint-preference-2236-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a desk organizer because ...',
    example_en = 'When I study or work, I use a desk organizer because it helps me stay organized.'
WHERE id = 'hint-preference-2237-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a ruler because ...',
    example_en = 'When I study or work, I use a ruler because it helps me stay organized.'
WHERE id = 'hint-preference-2238-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a file folder color because ...',
    example_en = 'When I study or work, I use a file folder color because it helps me stay organized.'
WHERE id = 'hint-preference-2239-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a small pouch for school or work because ...',
    example_en = 'When I study or work, I use a small pouch for school or work because it helps me stay organized.'
WHERE id = 'hint-preference-2240-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a keyboard style because ...',
    example_en = 'When I study or work, I use a keyboard style because it helps me stay organized.'
WHERE id = 'hint-preference-2241-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a mouse shape because ...',
    example_en = 'When I study or work, I use a mouse shape because it helps me stay organized.'
WHERE id = 'hint-preference-2242-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a desk timer because ...',
    example_en = 'When I study or work, I use a desk timer because it helps me stay organized.'
WHERE id = 'hint-preference-2243-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I keep papers organized by ... because ...',
    example_en = 'When I study or work, I keep papers organized by using folders because it helps me find things.'
WHERE id = 'hint-preference-2244-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a study tool because ...',
    example_en = 'When I study or work, I use a study tool because it helps me stay organized.'
WHERE id = 'hint-preference-2245-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a T-shirt color because ...',
    example_en = 'When I get dressed, I choose a T-shirt color because it feels comfortable.'
WHERE id = 'hint-preference-2246-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a hoodie style because ...',
    example_en = 'When I get dressed, I choose a hoodie style because it feels comfortable.'
WHERE id = 'hint-preference-2247-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a sock pattern because ...',
    example_en = 'When I get dressed, I choose a sock pattern because it feels comfortable.'
WHERE id = 'hint-preference-2248-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a pair of sneakers for daily use because ...',
    example_en = 'When I get dressed, I choose a pair of sneakers for daily use because it feels comfortable.'
WHERE id = 'hint-preference-2249-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a hat for sunny days because ...',
    example_en = 'When I get dressed, I choose a hat for sunny days because it feels comfortable.'
WHERE id = 'hint-preference-2250-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a scarf for winter because ...',
    example_en = 'When I get dressed, I choose a scarf for winter because it feels comfortable.'
WHERE id = 'hint-preference-2251-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a watch strap color because ...',
    example_en = 'When I go out, I carry a watch strap color because it makes my day easier.'
WHERE id = 'hint-preference-2252-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a pair of room slippers because ...',
    example_en = 'When I get dressed, I choose a pair of room slippers because it feels comfortable.'
WHERE id = 'hint-preference-2253-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a raincoat style because ...',
    example_en = 'When I get dressed, I choose a raincoat style because it feels comfortable.'
WHERE id = 'hint-preference-2254-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a pajama pattern because ...',
    example_en = 'When I get dressed, I choose a pajama pattern because it feels comfortable.'
WHERE id = 'hint-preference-2255-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a hair tie color because ...',
    example_en = 'When I get dressed, I choose a hair tie color because it feels comfortable.'
WHERE id = 'hint-preference-2256-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a umbrella style because ...',
    example_en = 'When I get dressed, I choose a umbrella style because it feels comfortable.'
WHERE id = 'hint-preference-2257-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a everyday jacket material because ...',
    example_en = 'When I get dressed, I choose a everyday jacket material because it feels comfortable.'
WHERE id = 'hint-preference-2258-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose a simple ring or bracelet because ...',
    example_en = 'When I get dressed, I choose a simple ring or bracelet because it feels comfortable.'
WHERE id = 'hint-preference-2259-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I get dressed, I choose something to wear when I want to feel relaxed because ...',
    example_en = 'When I get dressed, I choose something to wear when I want to feel relaxed because it feels comfortable.'
WHERE id = 'hint-preference-2260-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a blanket at home because ...',
    example_en = 'At home, I use a blanket at home because it makes my space more comfortable.'
WHERE id = 'hint-preference-2261-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a pillow because ...',
    example_en = 'At home, I use a pillow because it makes my space more comfortable.'
WHERE id = 'hint-preference-2262-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a mug because ...',
    example_en = 'At home, I use a mug because it makes my space more comfortable.'
WHERE id = 'hint-preference-2263-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a bowl because ...',
    example_en = 'When I cook or eat at home, I use a bowl because it is convenient.'
WHERE id = 'hint-preference-2264-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a lamp in my room because ...',
    example_en = 'At home, I use a lamp in my room because it makes my space more comfortable.'
WHERE id = 'hint-preference-2265-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a water bottle because ...',
    example_en = 'When I need something to drink, I choose a water bottle because it feels refreshing.'
WHERE id = 'hint-preference-2266-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a desk mat because ...',
    example_en = 'At home, I use a desk mat because it makes my space more comfortable.'
WHERE id = 'hint-preference-2267-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a chair cushion because ...',
    example_en = 'At home, I use a chair cushion because it makes my space more comfortable.'
WHERE id = 'hint-preference-2268-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a wall calendar design because ...',
    example_en = 'At home, I use a wall calendar design because it makes my space more comfortable.'
WHERE id = 'hint-preference-2269-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a small fan for my room because ...',
    example_en = 'At home, I use a small fan for my room because it makes my space more comfortable.'
WHERE id = 'hint-preference-2270-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a mirror because ...',
    example_en = 'At home, I use a mirror because it makes my space more comfortable.'
WHERE id = 'hint-preference-2271-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a storage basket because ...',
    example_en = 'At home, I use a storage basket because it makes my space more comfortable.'
WHERE id = 'hint-preference-2272-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a plate because ...',
    example_en = 'When I want something to eat, I choose a plate because it fits that moment.'
WHERE id = 'hint-preference-2273-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a small item in my room that helps me relax because ...',
    example_en = 'At home, I use a small item in my room that helps me relax because it makes my space more comfortable.'
WHERE id = 'hint-preference-2274-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a small thing on my bedside table because ...',
    example_en = 'At home, I use a small thing on my bedside table because it makes my space more comfortable.'
WHERE id = 'hint-preference-2275-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a hand cream scent because ...',
    example_en = 'When I take care of myself, I use a hand cream scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-2276-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a soap scent because ...',
    example_en = 'When I take care of myself, I use a soap scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-2277-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a shampoo scent because ...',
    example_en = 'When I take care of myself, I use a shampoo scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-2278-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a lip balm flavor or scent because ...',
    example_en = 'When I take care of myself, I use a lip balm flavor or scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-2279-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a body wash scent because ...',
    example_en = 'When I take care of myself, I use a body wash scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-2280-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a lotion texture because ...',
    example_en = 'When I take care of myself, I use a lotion texture because it helps me feel relaxed.'
WHERE id = 'hint-preference-2281-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a scent of freshly washed towels because ...',
    example_en = 'When I take care of myself, I use a scent of freshly washed towels because it helps me feel relaxed.'
WHERE id = 'hint-preference-2282-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a scent for bath salts because ...',
    example_en = 'When I take care of myself, I use a scent for bath salts because it helps me feel relaxed.'
WHERE id = 'hint-preference-2283-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a sunscreen type because ...',
    example_en = 'When I take care of myself, I use a sunscreen type because it helps me feel relaxed.'
WHERE id = 'hint-preference-2284-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a sheet mask because ...',
    example_en = 'When I take care of myself, I use a sheet mask because it helps me feel relaxed.'
WHERE id = 'hint-preference-2285-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a toothpaste flavor because ...',
    example_en = 'When I take care of myself, I use a toothpaste flavor because it helps me feel relaxed.'
WHERE id = 'hint-preference-2286-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a room spray scent because ...',
    example_en = 'When I take care of myself, I use a room spray scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-2287-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a hair oil scent because ...',
    example_en = 'When I take care of myself, I use a hair oil scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-2288-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a laundry detergent scent because ...',
    example_en = 'When I take care of myself, I use a laundry detergent scent because it helps me feel relaxed.'
WHERE id = 'hint-preference-2289-1-item-1';

UPDATE prompt_hint_items
SET content = 'Before bed, I use ... because it helps me ...',
    example_en = 'Before bed, I use hand cream because it helps me relax.'
WHERE id = 'hint-preference-2290-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a phone wallpaper style because ...',
    example_en = 'When I use my phone or an app, I choose a phone wallpaper style because it feels easy to use.'
WHERE id = 'hint-preference-2291-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a alarm sound because ...',
    example_en = 'When I use my phone or an app, I choose a alarm sound because it feels easy to use.'
WHERE id = 'hint-preference-2292-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a calendar view on my phone because ...',
    example_en = 'When I use my phone or an app, I choose a calendar view on my phone because it feels easy to use.'
WHERE id = 'hint-preference-2293-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a quick capture feature in a note-taking app because ...',
    example_en = 'When I use my phone or an app, I choose a quick capture feature in a note-taking app because it feels easy to use.'
WHERE id = 'hint-preference-2294-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a messaging sticker style because ...',
    example_en = 'When I need it, I choose a messaging sticker style because it helps me.'
WHERE id = 'hint-preference-2295-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a music app feature for making a queue because ...',
    example_en = 'When I use my phone or an app, I choose a music app feature for making a queue because it feels easy to use.'
WHERE id = 'hint-preference-2296-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a photo filter because ...',
    example_en = 'When I use my phone or an app, I choose a photo filter because it feels easy to use.'
WHERE id = 'hint-preference-2297-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a map app feature for checking my route or arrival time because ...',
    example_en = 'When I use my phone or an app, I choose a map app feature for checking my route or arrival time because it feels easy to use.'
WHERE id = 'hint-preference-2298-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a weather app view because ...',
    example_en = 'When I use my phone or an app, I choose a weather app view because it feels easy to use.'
WHERE id = 'hint-preference-2299-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a keyboard theme because ...',
    example_en = 'When I use my phone or an app, I choose a keyboard theme because it feels easy to use.'
WHERE id = 'hint-preference-2300-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a shortcut button on my phone because ...',
    example_en = 'When I use my phone or an app, I choose a shortcut button on my phone because it feels easy to use.'
WHERE id = 'hint-preference-2301-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a playlist cover style because ...',
    example_en = 'When I use my phone or an app, I choose a playlist cover style because it feels easy to use.'
WHERE id = 'hint-preference-2302-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a reminder app feature for repeating or snoozing reminders because ...',
    example_en = 'When I use my phone or an app, I choose a reminder app feature for repeating or snoozing reminders because it feels easy to use.'
WHERE id = 'hint-preference-2303-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a phone widget because ...',
    example_en = 'When I use my phone or an app, I choose a phone widget because it feels easy to use.'
WHERE id = 'hint-preference-2304-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose an app feature because ...',
    example_en = 'When I use my phone or an app, I choose an app feature because it feels easy to use.'
WHERE id = 'hint-preference-2305-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a bench in a small park because ...',
    example_en = 'When I need a short break, I choose a bench in a small park because it feels comfortable.'
WHERE id = 'hint-preference-2306-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose an aisle in a convenience store because ...',
    example_en = 'When I need a short break, I choose an aisle in a convenience store because it feels comfortable.'
WHERE id = 'hint-preference-2307-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a street near my home because ...',
    example_en = 'When I need a short break, I choose a street near my home because it feels comfortable.'
WHERE id = 'hint-preference-2308-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a flower stand near my home because ...',
    example_en = 'When I need a short break, I choose a flower stand near my home because it feels comfortable.'
WHERE id = 'hint-preference-2309-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a bus stop near my home because ...',
    example_en = 'When I need a short break, I choose a bus stop near my home because it feels comfortable.'
WHERE id = 'hint-preference-2310-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a seat near a train window because ...',
    example_en = 'When I need a short break, I choose a seat near a train window because it feels comfortable.'
WHERE id = 'hint-preference-2311-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a fruit stand near home because ...',
    example_en = 'When I want something to eat, I choose a fruit stand near home because it fits that moment.'
WHERE id = 'hint-preference-2312-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a path because ...',
    example_en = 'When I need a short break, I choose a path because it feels comfortable.'
WHERE id = 'hint-preference-2313-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a part of a market because ...',
    example_en = 'When I need a short break, I choose a part of a market because it feels comfortable.'
WHERE id = 'hint-preference-2314-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a vending machine near my home because ...',
    example_en = 'When I need a short break, I choose a vending machine near my home because it feels comfortable.'
WHERE id = 'hint-preference-2315-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a playground bench because ...',
    example_en = 'When I need a short break, I choose a playground bench because it feels comfortable.'
WHERE id = 'hint-preference-2316-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a nearby place because ...',
    example_en = 'When I need a short break, I choose a nearby place because it feels comfortable.'
WHERE id = 'hint-preference-2317-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a place near a window because ...',
    example_en = 'When I need a short break, I choose a place near a window because it feels comfortable.'
WHERE id = 'hint-preference-2318-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a small place because ...',
    example_en = 'When I need a short break, I choose a small place because it feels comfortable.'
WHERE id = 'hint-preference-2319-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a nearby place when I want a little fresh air because ...',
    example_en = 'When I need a short break, I choose a nearby place when I want a little fresh air because it feels comfortable.'
WHERE id = 'hint-preference-2320-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a simple puzzle because ...',
    example_en = 'When I take a break, I choose a simple puzzle because it helps me relax.'
WHERE id = 'hint-preference-2321-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a card game because ...',
    example_en = 'When I take a break, I choose a card game because it helps me relax.'
WHERE id = 'hint-preference-2322-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a type of YouTube video because ...',
    example_en = 'When I use my phone or an app, I choose a type of YouTube video because it feels easy to use.'
WHERE id = 'hint-preference-2323-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a podcast topic because ...',
    example_en = 'When I use my phone or an app, I choose a podcast topic because it feels easy to use.'
WHERE id = 'hint-preference-2324-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a coloring tool because ...',
    example_en = 'When I take a break, I choose a coloring tool because it helps me relax.'
WHERE id = 'hint-preference-2325-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a craft material because ...',
    example_en = 'When I take a break, I choose a craft material because it helps me relax.'
WHERE id = 'hint-preference-2326-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a simple photo edit because ...',
    example_en = 'When I take a break, I choose a simple photo edit because it helps me relax.'
WHERE id = 'hint-preference-2327-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a quick activity for a ten-minute break because ...',
    example_en = 'When I take a break, I choose a quick activity for a ten-minute break because it helps me relax.'
WHERE id = 'hint-preference-2328-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a small hobby for rainy days because ...',
    example_en = 'When I take a break, I choose a small hobby for rainy days because it helps me relax.'
WHERE id = 'hint-preference-2329-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a relaxing sound because ...',
    example_en = 'When I take a break, I choose a relaxing sound because it helps me relax.'
WHERE id = 'hint-preference-2330-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a indoor activity on hot days because ...',
    example_en = 'When I take a break, I choose a indoor activity on hot days because it helps me relax.'
WHERE id = 'hint-preference-2331-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a small thing because ...',
    example_en = 'When I need it, I choose a small thing because it helps me.'
WHERE id = 'hint-preference-2332-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a short video for learning something new because ...',
    example_en = 'When I use my phone or an app, I choose a short video for learning something new because it feels easy to use.'
WHERE id = 'hint-preference-2333-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a simple activity because ...',
    example_en = 'When I take a break, I choose a simple activity because it helps me relax.'
WHERE id = 'hint-preference-2334-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take a break, I choose a hobby because ...',
    example_en = 'When I take a break, I choose a hobby because it helps me relax.'
WHERE id = 'hint-preference-2335-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a water bottle for daily use because ...',
    example_en = 'When I go out, I carry a water bottle for daily use because it makes my day easier.'
WHERE id = 'hint-preference-2501-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a tumbler for refilling during the day because ...',
    example_en = 'When I need something to drink, I choose a tumbler for refilling during the day because it feels refreshing.'
WHERE id = 'hint-preference-2502-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a sparkling water flavor because ...',
    example_en = 'When I need it, I choose a sparkling water flavor because it helps me.'
WHERE id = 'hint-preference-2503-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a drink because ...',
    example_en = 'When I need something to drink, I choose a drink because it feels refreshing.'
WHERE id = 'hint-preference-2504-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a juice flavor because ...',
    example_en = 'When I need something to drink, I choose a juice flavor because it feels refreshing.'
WHERE id = 'hint-preference-2505-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a fruit because ...',
    example_en = 'When I want something to eat, I choose a fruit because it fits that moment.'
WHERE id = 'hint-preference-2506-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a bottle because ...',
    example_en = 'When I go out, I carry a bottle because it makes my day easier.'
WHERE id = 'hint-preference-2507-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a drink because ...',
    example_en = 'When I need something to drink, I choose a drink because it feels refreshing.'
WHERE id = 'hint-preference-2508-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a drink because ...',
    example_en = 'When I need something to drink, I choose a drink because it feels refreshing.'
WHERE id = 'hint-preference-2509-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a drink because ...',
    example_en = 'When I need something to drink, I choose a drink because it feels refreshing.'
WHERE id = 'hint-preference-2510-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a reusable cup for going out because ...',
    example_en = 'When I need it, I choose a reusable cup for going out because it helps me.'
WHERE id = 'hint-preference-2511-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a drink after light exercise because ...',
    example_en = 'When I need something to drink, I choose a drink after light exercise because it feels refreshing.'
WHERE id = 'hint-preference-2512-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a cold drink with ice on a hot day because ...',
    example_en = 'When I need something to drink, I choose a cold drink with ice on a hot day because it feels refreshing.'
WHERE id = 'hint-preference-2513-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I carry a bottle, I choose ... because ...',
    example_en = 'When I carry a bottle, I choose a slim bottle because it is easy to hold.'
WHERE id = 'hint-preference-2514-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a drink when I get home on a warm day because ...',
    example_en = 'When I need something to drink, I choose a drink when I get home on a warm day because it feels refreshing.'
WHERE id = 'hint-preference-2515-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a backpack for daily use because ...',
    example_en = 'When I need it, I choose a backpack for daily use because it helps me.'
WHERE id = 'hint-preference-2516-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a tote bag for a short trip because ...',
    example_en = 'When I go out, I carry a tote bag for a short trip because it makes my day easier.'
WHERE id = 'hint-preference-2517-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a small pouch in my bag because ...',
    example_en = 'When I go out, I carry a small pouch in my bag because it makes my day easier.'
WHERE id = 'hint-preference-2518-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a wallet for daily use because ...',
    example_en = 'When I go out, I carry a wallet for daily use because it makes my day easier.'
WHERE id = 'hint-preference-2519-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a keychain because ...',
    example_en = 'When I go out, I carry a keychain because it makes my day easier.'
WHERE id = 'hint-preference-2520-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a bag pocket for carrying a water bottle because ...',
    example_en = 'When I need something to drink, I choose a bag pocket for carrying a water bottle because it feels refreshing.'
WHERE id = 'hint-preference-2521-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a bag zipper because ...',
    example_en = 'When I go out, I carry a bag zipper because it makes my day easier.'
WHERE id = 'hint-preference-2522-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a cardholder because ...',
    example_en = 'When I go out, I carry a cardholder because it makes my day easier.'
WHERE id = 'hint-preference-2523-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a bag strap because ...',
    example_en = 'When I go out, I carry a bag strap because it makes my day easier.'
WHERE id = 'hint-preference-2524-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a everyday bag because ...',
    example_en = 'When I go out, I carry a everyday bag because it makes my day easier.'
WHERE id = 'hint-preference-2525-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a foldable shopping bag because ...',
    example_en = 'When I go out, I carry a foldable shopping bag because it makes my day easier.'
WHERE id = 'hint-preference-2526-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a portable charger because ...',
    example_en = 'When I go out, I carry a portable charger because it makes my day easier.'
WHERE id = 'hint-preference-2527-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I study or work, I use a pouch for pens or cables because ...',
    example_en = 'When I study or work, I use a pouch for pens or cables because it helps me stay organized.'
WHERE id = 'hint-preference-2528-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a bag because ...',
    example_en = 'When I go out, I carry a bag because it makes my day easier.'
WHERE id = 'hint-preference-2529-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a small bag for a quick trip outside because ...',
    example_en = 'When I go out, I carry a small bag for a quick trip outside because it makes my day easier.'
WHERE id = 'hint-preference-2530-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a storage box at home because ...',
    example_en = 'At home, I use a storage box at home because it makes my space more comfortable.'
WHERE id = 'hint-preference-2531-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a hanger type for daily clothes because ...',
    example_en = 'At home, I use a hanger type for daily clothes because it makes my space more comfortable.'
WHERE id = 'hint-preference-2532-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a drawer organizer because ...',
    example_en = 'At home, I use a drawer organizer because it makes my space more comfortable.'
WHERE id = 'hint-preference-2533-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a wall hook because ...',
    example_en = 'At home, I use a wall hook because it makes my space more comfortable.'
WHERE id = 'hint-preference-2534-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a box for small items because ...',
    example_en = 'At home, I use a box for small items because it makes my space more comfortable.'
WHERE id = 'hint-preference-2535-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a cleaning cloth for my desk because ...',
    example_en = 'When I need it, I choose a cleaning cloth for my desk because it helps me.'
WHERE id = 'hint-preference-2536-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a spray bottle for easy cleaning because ...',
    example_en = 'When I need something to drink, I choose a spray bottle for easy cleaning because it feels refreshing.'
WHERE id = 'hint-preference-2537-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a sponge for the kitchen because ...',
    example_en = 'When I cook or eat at home, I use a sponge for the kitchen because it is convenient.'
WHERE id = 'hint-preference-2538-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a small shelf in my room because ...',
    example_en = 'At home, I use a small shelf in my room because it makes my space more comfortable.'
WHERE id = 'hint-preference-2539-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a label because ...',
    example_en = 'At home, I use a label because it makes my space more comfortable.'
WHERE id = 'hint-preference-2540-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a organizer for a bathroom drawer because ...',
    example_en = 'At home, I use a organizer for a bathroom drawer because it makes my space more comfortable.'
WHERE id = 'hint-preference-2541-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a shoe box because ...',
    example_en = 'At home, I use a shoe box because it makes my space more comfortable.'
WHERE id = 'hint-preference-2542-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a box because ...',
    example_en = 'At home, I use a box because it makes my space more comfortable.'
WHERE id = 'hint-preference-2543-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I take care of myself, I use a basket because ...',
    example_en = 'When I take care of myself, I use a basket because it helps me feel relaxed.'
WHERE id = 'hint-preference-2544-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I go out, I carry a hook near the door for bags or keys because ...',
    example_en = 'When I go out, I carry a hook near the door for bags or keys because it makes my day easier.'
WHERE id = 'hint-preference-2545-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a phone charger at home because ...',
    example_en = 'When I use my phone or an app, I choose a phone charger at home because it feels easy to use.'
WHERE id = 'hint-preference-2546-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a cable length for daily use because ...',
    example_en = 'When I need it, I choose a cable length for daily use because it helps me.'
WHERE id = 'hint-preference-2547-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a small speaker for background music because ...',
    example_en = 'At home, I use a small speaker for background music because it makes my space more comfortable.'
WHERE id = 'hint-preference-2548-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a desk fan for warm days because ...',
    example_en = 'At home, I use a desk fan for warm days because it makes my space more comfortable.'
WHERE id = 'hint-preference-2549-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a alarm clock style because ...',
    example_en = 'When I need it, I choose a alarm clock style because it helps me.'
WHERE id = 'hint-preference-2550-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I use my phone or an app, I choose a phone stand on my desk because ...',
    example_en = 'When I use my phone or an app, I choose a phone stand on my desk because it feels easy to use.'
WHERE id = 'hint-preference-2551-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a bedside lamp because ...',
    example_en = 'At home, I use a bedside lamp because it makes my space more comfortable.'
WHERE id = 'hint-preference-2552-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need it, I choose a timer for short tasks because ...',
    example_en = 'When I need it, I choose a timer for short tasks because it helps me.'
WHERE id = 'hint-preference-2553-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a compact humidifier because ...',
    example_en = 'At home, I use a compact humidifier because it makes my space more comfortable.'
WHERE id = 'hint-preference-2554-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a power strip at home because ...',
    example_en = 'At home, I use a power strip at home because it makes my space more comfortable.'
WHERE id = 'hint-preference-2555-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a reading lamp because ...',
    example_en = 'At home, I use a reading lamp because it makes my space more comfortable.'
WHERE id = 'hint-preference-2556-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a charger because ...',
    example_en = 'At home, I use a charger because it makes my space more comfortable.'
WHERE id = 'hint-preference-2557-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a portable fan because ...',
    example_en = 'At home, I use a portable fan because it makes my space more comfortable.'
WHERE id = 'hint-preference-2558-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need a short break, I choose a tablet stand because ...',
    example_en = 'When I need a short break, I choose a tablet stand because it feels comfortable.'
WHERE id = 'hint-preference-2559-1-item-1';

UPDATE prompt_hint_items
SET content = 'At home, I use a clip-on lamp for a desk or bed because ...',
    example_en = 'At home, I use a clip-on lamp for a desk or bed because it makes my space more comfortable.'
WHERE id = 'hint-preference-2560-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a food container for leftovers because ...',
    example_en = 'When I want something to eat, I choose a food container for leftovers because it fits that moment.'
WHERE id = 'hint-preference-2561-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a food container because ...',
    example_en = 'When I want something to eat, I choose a food container because it fits that moment.'
WHERE id = 'hint-preference-2562-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a food container for lunch because ...',
    example_en = 'When I want something to eat, I choose a food container for lunch because it fits that moment.'
WHERE id = 'hint-preference-2563-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a spoon because ...',
    example_en = 'When I want something to eat, I choose a spoon because it fits that moment.'
WHERE id = 'hint-preference-2564-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a pair of chopsticks because ...',
    example_en = 'When I cook or eat at home, I use a pair of chopsticks because it is convenient.'
WHERE id = 'hint-preference-2565-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a small tray for snacks because ...',
    example_en = 'When I want something to eat, I choose a small tray for snacks because it fits that moment.'
WHERE id = 'hint-preference-2566-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a easy-to-wash cutting board because ...',
    example_en = 'When I cook or eat at home, I use a easy-to-wash cutting board because it is convenient.'
WHERE id = 'hint-preference-2567-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a kitchen towel because ...',
    example_en = 'When I cook or eat at home, I use a kitchen towel because it is convenient.'
WHERE id = 'hint-preference-2568-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a kettle at home because ...',
    example_en = 'When I cook or eat at home, I use a kettle at home because it is convenient.'
WHERE id = 'hint-preference-2569-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I need something to drink, I choose a thermos for a warm drink because ...',
    example_en = 'When I need something to drink, I choose a thermos for a warm drink because it feels refreshing.'
WHERE id = 'hint-preference-2570-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a container because ...',
    example_en = 'When I want something to eat, I choose a container because it fits that moment.'
WHERE id = 'hint-preference-2571-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a container for small frozen foods because ...',
    example_en = 'When I want something to eat, I choose a container for small frozen foods because it fits that moment.'
WHERE id = 'hint-preference-2572-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a lunch box because ...',
    example_en = 'When I want something to eat, I choose a lunch box because it fits that moment.'
WHERE id = 'hint-preference-2573-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I cook or eat at home, I use a thermos because ...',
    example_en = 'When I cook or eat at home, I use a thermos because it is convenient.'
WHERE id = 'hint-preference-2574-1-item-1';

UPDATE prompt_hint_items
SET content = 'When I want something to eat, I choose a little container for sauce or snacks because ...',
    example_en = 'When I want something to eat, I choose a little container for sauce or snacks because it fits that moment.'
WHERE id = 'hint-preference-2575-1-item-1';
