-- Broaden micro preference prompts so they ask about situations, routines, and reasons.
-- This follows 069, expanding the same quality guardrail beyond stationery prompts.

START TRANSACTION;

CREATE TEMPORARY TABLE prompt_micro_preference_reframes (
    id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci PRIMARY KEY,
    question_en TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    question_ko TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    tip TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
);

INSERT INTO prompt_micro_preference_reframes (id, question_en, question_ko, tip) VALUES
    ('prompt-preference-2201', 'What makes breakfast easy to eat on a busy morning?', '바쁜 아침에 먹기 쉬운 아침 식사는 어떤 모습인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2202', 'How do you like to add protein or energy to breakfast?', '아침 식사에 단백질이나 에너지를 더하려면 보통 어떻게 하나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2204', 'What do you add to a simple breakfast to make it more enjoyable?', '간단한 아침 식사를 더 즐겁게 만들기 위해 무엇을 더하나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2205', 'What kind of quick breakfast helps you start the day?', '하루를 시작하는 데 도움이 되는 빠른 아침 식사는 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2206', 'What flavor makes a simple breakfast feel better?', '간단한 아침 식사를 더 기분 좋게 만드는 맛은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2207', 'How do you make toast or a simple breakfast feel more complete?', '토스트나 간단한 아침 식사를 더 든든하게 만들려면 어떻게 하나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2208', 'What simple meal works when you do not have much time?', '시간이 별로 없을 때 잘 맞는 간단한 식사는 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2213', 'What do you put on rice or a simple meal to make it satisfying?', '밥이나 간단한 식사를 더 만족스럽게 만들기 위해 무엇을 올리나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2214', 'What would you eat on a quiet morning when you want something gentle?', '조용한 아침에 부담 없는 음식을 먹고 싶다면 무엇을 고르나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2215', 'What quick meal helps when your morning starts late?', '아침이 늦게 시작된 날에는 어떤 빠른 식사가 도움이 되나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2216', 'What small snack feels right during a short break?', '짧게 쉴 때 잘 맞는 작은 간식은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2217', 'What crunchy snack do you reach for when you want a quick break?', '잠깐 쉬고 싶을 때 손이 가는 바삭한 간식은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2218', 'What cold treat would you choose on a warm or tiring day?', '덥거나 피곤한 날에는 어떤 차가운 간식을 고르고 싶나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2219', 'What sweet snack feels good after studying or working?', '공부나 일을 마친 뒤 기분 좋게 먹을 수 있는 달콤한 간식은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2220', 'What small sweet would you choose when you want a little energy?', '조금 힘을 내고 싶을 때 어떤 작은 단 간식을 고르나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2221', 'What would you pick from a convenience store during a busy day?', '바쁜 하루 중 편의점에 들른다면 무엇을 고르고 싶나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2222', 'What simple snack is easy to share or eat while relaxing?', '쉬는 동안 먹거나 나누기 쉬운 간단한 간식은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2223', 'What snack would you choose while watching a movie or show?', '영화나 영상을 볼 때 어떤 간식을 고르고 싶나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2225', 'What drink snack feels refreshing during the day?', '하루 중 상쾌하게 마시거나 먹기 좋은 간식은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2226', 'What sweet fruit flavor reminds you of a good break?', '좋은 휴식을 떠올리게 하는 달콤한 과일 맛은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2227', 'What would you eat late at night when you want something small?', '늦은 밤에 조금만 먹고 싶을 때 무엇을 고르나요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2228', 'What salty snack fits a casual break, and why?', '가볍게 쉬는 시간에 잘 맞는 짭짤한 간식은 무엇인가요? 이유도 말해 주세요.', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2229', 'What soft snack would feel comforting after a long day?', '긴 하루 뒤에 위로가 될 만한 부드러운 간식은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2230', 'What small treat would help you end the day in a good mood?', '하루를 기분 좋게 마무리하게 해 줄 작은 간식은 무엇인가요?', '음식 이름만 말하지 말고, 언제 먹는지와 그 순간에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2246', 'How do you choose what to wear when you want to feel comfortable and ready?', '편안하면서도 준비된 느낌을 받고 싶을 때 옷을 어떻게 고르나요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2247', 'What do you wear when you want to feel warm but relaxed?', '따뜻하면서도 편하게 있고 싶을 때 무엇을 입나요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2248', 'What small clothing detail can make an outfit feel more fun or comfortable?', '옷차림을 더 즐겁거나 편하게 만들어 주는 작은 요소는 무엇인가요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2249', 'What makes shoes comfortable for a normal day outside?', '평범한 외출 날에 신발이 편하게 느껴지려면 무엇이 중요할까요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2250', 'How do you prepare for strong sunlight when you go out?', '햇빛이 강한 날 외출할 때 어떻게 준비하나요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2251', 'What helps you stay warm on a cold day without feeling uncomfortable?', '추운 날 불편하지 않게 따뜻함을 유지하려면 무엇이 도움이 되나요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2252', 'What everyday accessory makes your outfit or routine feel easier?', '매일 쓰는 액세서리 중 옷차림이나 루틴을 더 편하게 해 주는 것은 무엇인가요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2253', 'What do you wear at home when you want your feet to feel comfortable?', '집에서 발이 편하게 느껴지려면 무엇을 신나요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2254', 'What helps you stay comfortable when it rains?', '비가 올 때 편하게 지내는 데 도움이 되는 것은 무엇인가요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2255', 'What makes bedtime clothes feel relaxing to you?', '잠잘 때 입는 옷이 편안하게 느껴지려면 무엇이 중요할까요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2256', 'What helps you keep your hair comfortable during a busy day?', '바쁜 하루 동안 머리를 편하게 유지하는 데 도움이 되는 것은 무엇인가요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2257', 'What do you bring or wear when the weather might change?', '날씨가 바뀔 수 있는 날에는 무엇을 챙기거나 입나요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2258', 'What kind of jacket works well for your everyday routine?', '일상 루틴에 잘 맞는 재킷은 어떤 점이 좋아야 하나요?', '색이나 모양만 말하지 말고, 날씨나 장소, 기분 같은 상황을 함께 말해 보세요.'),
    ('prompt-preference-2261', 'What helps you feel comfortable when you rest at home, and why?', '집에서 쉴 때 편안함을 느끼게 해 주는 것은 무엇인가요? 이유도 말해 주세요.', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2262', 'What makes your sleep or rest feel better at home?', '집에서 잠을 자거나 쉴 때 더 편하게 느끼게 해 주는 것은 무엇인가요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2263', 'What small part of your drink routine makes home feel more relaxing?', '집에서 마시는 음료 루틴 중 어떤 점이 더 편안하게 느껴지게 하나요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2265', 'How does lighting change the way you study, rest, or spend time in your room?', '방의 조명은 공부하거나 쉬거나 시간을 보내는 방식에 어떤 영향을 주나요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2266', 'What helps you remember to drink water at home, and when do you need it most?', '집에서 물 마시는 것을 기억하게 해 주는 것은 무엇인가요? 언제 가장 필요하나요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2267', 'What makes your desk feel easier to use during study or work?', '공부나 일을 할 때 책상을 더 쓰기 편하게 만드는 것은 무엇인가요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2268', 'What helps you sit comfortably when you read, study, or relax?', '책을 읽거나 공부하거나 쉴 때 편하게 앉는 데 도움이 되는 것은 무엇인가요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2269', 'How do you keep track of plans at home, and why does that method help?', '집에서 계획을 어떻게 확인하나요? 그 방법이 왜 도움이 되나요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2270', 'What helps your room feel cooler or more comfortable on warm days?', '더운 날 방을 더 시원하거나 편하게 느끼게 해 주는 것은 무엇인가요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2272', 'How do you keep everyday items easy to find at home?', '집에서 자주 쓰는 물건을 찾기 쉽게 두려면 어떻게 하나요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2274', 'What small thing makes your room feel more relaxing after a long day?', '긴 하루 뒤에 방을 더 편안하게 느끼게 해 주는 작은 것은 무엇인가요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2275', 'What do you like to keep near your bed, and how does it help your night routine?', '침대 근처에 두고 싶은 것은 무엇인가요? 밤 루틴에 어떻게 도움이 되나요?', '물건 이름만 말하지 말고, 어떤 순간에 루틴이 편해지는지와 그 이유를 함께 말해 보세요.'),
    ('prompt-preference-2276', 'What makes your hands feel cared for during the day?', '하루 중 손이 잘 관리되고 있다고 느끼게 해 주는 것은 무엇인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2277', 'What kind of clean feeling do you like after washing your hands?', '손을 씻은 뒤 어떤 깔끔한 느낌을 좋아하나요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2278', 'What makes washing your hair feel refreshing or relaxing?', '머리를 감는 시간이 상쾌하거나 편안하게 느껴지려면 무엇이 중요한가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2279', 'What do you use when your lips feel dry, and why?', '입술이 건조할 때 무엇을 사용하나요? 이유도 말해 주세요.', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2280', 'What helps you feel fresh after a shower?', '샤워 후 상쾌함을 느끼게 해 주는 것은 무엇인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2281', 'What kind of texture feels comfortable on your skin?', '피부에 닿았을 때 편안하게 느껴지는 질감은 어떤 것인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2282', 'What small detail makes clean towels feel pleasant to use?', '깨끗한 수건을 사용할 때 기분 좋게 느껴지는 작은 요소는 무엇인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2283', 'What helps bath time feel more relaxing?', '목욕이나 샤워 시간이 더 편안하게 느껴지도록 돕는 것은 무엇인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2284', 'How do you protect your skin before going outside?', '외출하기 전에 피부를 보호하기 위해 어떻게 하나요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2285', 'What helps your face feel refreshed after a long day?', '긴 하루 뒤에 얼굴이 산뜻해지도록 도와주는 것은 무엇인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2286', 'What makes brushing your teeth feel fresh in the morning or at night?', '아침이나 밤에 이를 닦을 때 상쾌하게 느껴지게 하는 것은 무엇인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2287', 'What helps your room smell clean or relaxing?', '방에서 깨끗하거나 편안한 향이 나게 하려면 무엇이 도움이 되나요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2288', 'What helps your hair feel neat or soft after washing?', '머리를 감은 뒤 머리가 단정하거나 부드럽게 느껴지도록 돕는 것은 무엇인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2289', 'What makes clean clothes feel pleasant to wear?', '깨끗한 옷을 입을 때 기분 좋게 느껴지는 이유는 무엇인가요?', '향이나 제품명만 말하지 말고, 언제 쓰는지와 사용 후 어떤 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-preference-2291', 'What phone screen setup helps you start the day smoothly?', '하루를 부드럽게 시작하는 데 도움이 되는 휴대폰 화면 구성은 무엇인가요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2292', 'What kind of alarm helps you wake up or move on to the next task?', '일어나거나 다음 일로 넘어갈 때 도움이 되는 알람은 어떤 것인가요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2293', 'How do you use your calendar to keep the day organized?', '하루를 정리된 상태로 보내기 위해 캘린더를 어떻게 사용하나요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2294', 'What quick note habit helps you remember ideas or tasks?', '아이디어나 할 일을 기억하는 데 도움이 되는 빠른 메모 습관은 무엇인가요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2295', 'How do messages or stickers help you communicate with friends?', '메시지나 스티커는 친구들과 소통할 때 어떻게 도움이 되나요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2296', 'What helps you choose music for studying, resting, or moving around?', '공부하거나 쉬거나 이동할 때 음악을 고르는 데 도움이 되는 것은 무엇인가요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2297', 'How do photo filters change the way you save everyday moments?', '사진 필터는 일상의 순간을 저장하는 방식에 어떤 영향을 주나요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2298', 'What map feature helps when you need to go somewhere new?', '새로운 곳에 가야 할 때 어떤 지도 기능이 도움이 되나요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2299', 'What weather app information do you check before going out?', '외출하기 전에 날씨 앱에서 어떤 정보를 확인하나요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2300', 'What phone setting makes typing feel easier or more comfortable?', '휴대폰에서 타이핑을 더 쉽거나 편하게 만드는 설정은 무엇인가요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2301', 'What shortcut on your phone saves you time during the day?', '하루 중 시간을 아껴 주는 휴대폰 바로가기는 무엇인가요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2302', 'How do you make a playlist feel right for a certain mood or moment?', '특정 기분이나 순간에 맞는 플레이리스트를 어떻게 만드나요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2303', 'What reminder helps you avoid forgetting small tasks?', '작은 할 일을 잊지 않게 해 주는 리마인더는 무엇인가요?', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2304', 'What phone widget would you keep on your home screen, and why?', '휴대폰 홈 화면에 어떤 위젯을 두고 싶나요? 이유도 말해 주세요.', '기능 이름보다 언제 쓰는지와 어떤 점이 더 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2516', 'What kind of bag setup helps you move through a busy day?', '바쁜 하루를 보내는 데 도움이 되는 가방 구성은 무엇인가요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2517', 'What do you carry for a short trip outside, and why?', '잠깐 외출할 때 무엇을 챙기나요? 이유도 말해 주세요.', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2518', 'How do you organize small things in your bag so they are easy to find?', '가방 속 작은 물건을 찾기 쉽게 정리하려면 어떻게 하나요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2519', 'What do you need to keep close when you pay, travel, or run errands?', '결제하거나 이동하거나 볼일을 볼 때 가까이 두어야 하는 것은 무엇인가요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2521', 'How do you carry water when you are out for a long time?', '오래 외출할 때 물을 어떻게 챙기나요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2522', 'What makes opening and closing your bag feel easy during the day?', '하루 중 가방을 열고 닫을 때 편하게 느껴지게 하는 것은 무엇인가요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2523', 'What helps you carry only the cards or money you really need?', '꼭 필요한 카드나 돈만 간단히 챙기는 데 도움이 되는 것은 무엇인가요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2524', 'What makes a bag comfortable to carry for a long time?', '가방을 오래 들고 다녀도 편하게 느껴지려면 무엇이 중요할까요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2525', 'What everyday bag works best for your normal routine, and why?', '평소 루틴에 가장 잘 맞는 데일리 가방은 어떤 것인가요? 이유도 말해 주세요.', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2526', 'What do you bring when you might shop or pick something up later?', '나중에 장을 보거나 물건을 챙길 일이 있을 때 무엇을 가져가나요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2528', 'How do you keep pens, cables, or small tools from getting lost?', '펜, 케이블, 작은 도구가 없어지지 않도록 어떻게 보관하나요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2530', 'What would you pack for a quick walk or short errand?', '짧은 산책이나 간단한 볼일을 위해 무엇을 챙기나요?', '무엇을 챙기는지와 이동 중 어떤 점이 편해지는지를 함께 말해 보세요.'),
    ('prompt-preference-2531', 'How do you store things at home so your room feels less messy?', '방이 덜 어수선하게 느껴지도록 집에서 물건을 어떻게 보관하나요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2532', 'How do you organize clothes you use often?', '자주 입는 옷은 어떻게 정리하나요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2533', 'What helps you keep a drawer easy to use?', '서랍을 쓰기 편하게 유지하는 데 도움이 되는 것은 무엇인가요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2535', 'Where do you keep small items that are easy to lose?', '잃어버리기 쉬운 작은 물건은 어디에 보관하나요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2536', 'What helps you clean your desk quickly before study or work?', '공부나 일을 시작하기 전에 책상을 빠르게 정리하는 데 도움이 되는 것은 무엇인가요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2537', 'What makes small cleaning jobs at home easier to start?', '집에서 작은 청소를 더 쉽게 시작하게 해 주는 것은 무엇인가요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2538', 'What do you use to clean up after cooking or washing dishes?', '요리하거나 설거지한 뒤 정리할 때 무엇을 사용하나요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2539', 'What kind of storage space would make your room easier to use?', '방을 더 쓰기 편하게 만들어 줄 수납 공간은 어떤 것인가요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2541', 'What helps you organize small things in the bathroom?', '욕실의 작은 물건을 정리하는 데 도움이 되는 것은 무엇인가요?', '정리 도구 이름보다 무엇을 어디에 두고 왜 찾기 쉬워지는지를 말해 보세요.'),
    ('prompt-preference-2545', 'What helps you keep bags or keys ready near the door?', '문 근처에 가방이나 열쇠를 바로 챙길 수 있게 두려면 무엇이 도움이 되나요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2546', 'How do you set up phone charging so it does not interrupt your day?', '하루 중 휴대폰 충전이 방해되지 않게 하려면 어떻게 준비하나요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2547', 'What cable setup would make your daily devices easier to use?', '매일 쓰는 기기를 더 편하게 사용하게 해 주는 케이블 구성은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2548', 'What background sound helps you focus or relax at home?', '집에서 집중하거나 쉴 때 도움이 되는 배경 소리는 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2549', 'What helps you stay comfortable at your desk on warm days?', '더운 날 책상에 앉아 있을 때 편하게 지내는 데 도움이 되는 것은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2550', 'What kind of alarm setup helps you move through your routine?', '루틴을 따라 움직이는 데 도움이 되는 알람 설정은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2551', 'How do you keep your phone easy to see while studying or cooking?', '공부하거나 요리할 때 휴대폰을 보기 쉽게 두려면 어떻게 하나요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2552', 'What kind of light helps you read or rest at night?', '밤에 책을 읽거나 쉴 때 도움이 되는 조명은 어떤 것인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2553', 'What helps you keep track of short tasks without feeling stressed?', '짧은 할 일을 부담 없이 확인하는 데 도움이 되는 것은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2554', 'What helps your room feel comfortable when the air feels dry?', '공기가 건조할 때 방을 더 편하게 느끼게 해 주는 것은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2555', 'How do you set up plugs or chargers so your space stays tidy?', '공간이 지저분해지지 않도록 콘센트나 충전기를 어떻게 정리하나요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2556', 'What lighting helps you read without getting tired?', '눈이 덜 피곤하게 책을 읽도록 도와주는 조명은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2558', 'What helps you stay cool when you are outside or moving around?', '밖에 있거나 이동할 때 시원하게 지내는 데 도움이 되는 것은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2559', 'What stand or holder helps you use a tablet more comfortably?', '태블릿을 더 편하게 쓰도록 도와주는 거치 방식은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2560', 'What kind of small light would help in a dark desk or bedside area?', '어두운 책상이나 침대 옆에서 도움이 되는 작은 조명은 어떤 것인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2561', 'What helps you keep food fresh after a meal?', '식사 후 남은 음식을 신선하게 보관하는 데 도움이 되는 것은 무엇인가요?', '기기나 도구 이름만 말하지 말고, 어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2563', 'What kind of lunch container helps you eat comfortably away from home?', '집 밖에서 편하게 점심을 먹도록 도와주는 도시락 용기는 어떤 것인가요?', '주방 도구 이름보다 어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2566', 'What makes preparing food feel easier and less messy?', '음식을 준비할 때 더 쉽고 덜 어지럽게 만들어 주는 것은 무엇인가요?', '주방 도구 이름보다 어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2567', 'What do you use to clean up small spills or wet hands in the kitchen?', '주방에서 작은 물기나 젖은 손을 정리할 때 무엇을 사용하나요?', '주방 도구 이름보다 어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2568', 'How do you prepare a warm drink at home when you want to relax?', '집에서 쉬고 싶을 때 따뜻한 음료를 어떻게 준비하나요?', '주방 도구 이름보다 어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2569', 'What helps you keep a warm drink with you for longer?', '따뜻한 음료를 더 오래 곁에 두는 데 도움이 되는 것은 무엇인가요?', '주방 도구 이름보다 어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2570', 'How do you store frozen food so it is easy to use later?', '나중에 쓰기 쉽도록 냉동식품을 어떻게 보관하나요?', '주방 도구 이름보다 어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2572', 'What helps you carry or store small sauces or snacks neatly?', '작은 소스나 간식을 깔끔하게 담거나 챙기는 데 도움이 되는 것은 무엇인가요?', '주방 도구 이름보다 어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2575', 'What helps you keep kitchen tasks simple on a busy day?', '바쁜 날 주방 일을 간단하게 유지하는 데 도움이 되는 것은 무엇인가요?', '주방 도구 이름보다 어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.');

UPDATE prompts p
JOIN prompt_micro_preference_reframes r ON r.id = p.id
SET p.question_en = r.question_en,
    p.question_ko = r.question_ko,
    p.tip = r.tip;

-- Refresh the primary starter hint so the guide matches the broader situation-focused prompts.
UPDATE prompt_hint_items SET content = 'I usually choose or use this when ... because ...',
    meaning_ko = '상황과 이유를 함께 말하는 시작 문장',
    usage_tip_ko = '물건 이름만 따라 쓰지 말고, 실제 상황과 이유를 내 문장으로 바꿔 써 보세요.',
    example_en = 'I usually use this when my day feels busy because it keeps things simple.'
WHERE id IN (
    'hint-preference-2201-1-item-1',
    'hint-preference-2202-1-item-1',
    'hint-preference-2204-1-item-1',
    'hint-preference-2205-1-item-1',
    'hint-preference-2206-1-item-1',
    'hint-preference-2207-1-item-1',
    'hint-preference-2208-1-item-1',
    'hint-preference-2213-1-item-1',
    'hint-preference-2214-1-item-1',
    'hint-preference-2215-1-item-1',
    'hint-preference-2216-1-item-1',
    'hint-preference-2217-1-item-1',
    'hint-preference-2218-1-item-1',
    'hint-preference-2219-1-item-1',
    'hint-preference-2220-1-item-1',
    'hint-preference-2221-1-item-1',
    'hint-preference-2222-1-item-1',
    'hint-preference-2223-1-item-1',
    'hint-preference-2225-1-item-1',
    'hint-preference-2226-1-item-1',
    'hint-preference-2227-1-item-1',
    'hint-preference-2228-1-item-1',
    'hint-preference-2229-1-item-1',
    'hint-preference-2230-1-item-1',
    'hint-preference-2246-1-item-1',
    'hint-preference-2247-1-item-1',
    'hint-preference-2248-1-item-1',
    'hint-preference-2249-1-item-1',
    'hint-preference-2250-1-item-1',
    'hint-preference-2251-1-item-1',
    'hint-preference-2252-1-item-1',
    'hint-preference-2253-1-item-1',
    'hint-preference-2254-1-item-1',
    'hint-preference-2255-1-item-1',
    'hint-preference-2256-1-item-1',
    'hint-preference-2257-1-item-1',
    'hint-preference-2258-1-item-1',
    'hint-preference-2261-1-item-1',
    'hint-preference-2262-1-item-1',
    'hint-preference-2263-1-item-1',
    'hint-preference-2265-1-item-1',
    'hint-preference-2266-1-item-1',
    'hint-preference-2267-1-item-1',
    'hint-preference-2268-1-item-1',
    'hint-preference-2269-1-item-1',
    'hint-preference-2270-1-item-1',
    'hint-preference-2272-1-item-1',
    'hint-preference-2274-1-item-1',
    'hint-preference-2275-1-item-1',
    'hint-preference-2276-1-item-1',
    'hint-preference-2277-1-item-1',
    'hint-preference-2278-1-item-1',
    'hint-preference-2279-1-item-1',
    'hint-preference-2280-1-item-1',
    'hint-preference-2281-1-item-1',
    'hint-preference-2282-1-item-1',
    'hint-preference-2283-1-item-1',
    'hint-preference-2284-1-item-1',
    'hint-preference-2285-1-item-1',
    'hint-preference-2286-1-item-1',
    'hint-preference-2287-1-item-1',
    'hint-preference-2288-1-item-1',
    'hint-preference-2289-1-item-1',
    'hint-preference-2291-1-item-1',
    'hint-preference-2292-1-item-1',
    'hint-preference-2293-1-item-1',
    'hint-preference-2294-1-item-1',
    'hint-preference-2295-1-item-1',
    'hint-preference-2296-1-item-1',
    'hint-preference-2297-1-item-1',
    'hint-preference-2298-1-item-1',
    'hint-preference-2299-1-item-1',
    'hint-preference-2300-1-item-1',
    'hint-preference-2301-1-item-1',
    'hint-preference-2302-1-item-1',
    'hint-preference-2303-1-item-1',
    'hint-preference-2304-1-item-1',
    'hint-preference-2516-1-item-1',
    'hint-preference-2517-1-item-1',
    'hint-preference-2518-1-item-1',
    'hint-preference-2519-1-item-1',
    'hint-preference-2521-1-item-1',
    'hint-preference-2522-1-item-1',
    'hint-preference-2523-1-item-1',
    'hint-preference-2524-1-item-1',
    'hint-preference-2525-1-item-1',
    'hint-preference-2526-1-item-1',
    'hint-preference-2528-1-item-1',
    'hint-preference-2530-1-item-1',
    'hint-preference-2531-1-item-1',
    'hint-preference-2532-1-item-1',
    'hint-preference-2533-1-item-1',
    'hint-preference-2535-1-item-1',
    'hint-preference-2536-1-item-1',
    'hint-preference-2537-1-item-1',
    'hint-preference-2538-1-item-1',
    'hint-preference-2539-1-item-1',
    'hint-preference-2541-1-item-1',
    'hint-preference-2545-1-item-1',
    'hint-preference-2546-1-item-1',
    'hint-preference-2547-1-item-1',
    'hint-preference-2548-1-item-1',
    'hint-preference-2549-1-item-1',
    'hint-preference-2550-1-item-1',
    'hint-preference-2551-1-item-1',
    'hint-preference-2552-1-item-1',
    'hint-preference-2553-1-item-1',
    'hint-preference-2554-1-item-1',
    'hint-preference-2555-1-item-1',
    'hint-preference-2556-1-item-1',
    'hint-preference-2558-1-item-1',
    'hint-preference-2559-1-item-1',
    'hint-preference-2560-1-item-1',
    'hint-preference-2561-1-item-1',
    'hint-preference-2563-1-item-1',
    'hint-preference-2566-1-item-1',
    'hint-preference-2567-1-item-1',
    'hint-preference-2568-1-item-1',
    'hint-preference-2569-1-item-1',
    'hint-preference-2570-1-item-1',
    'hint-preference-2572-1-item-1',
    'hint-preference-2575-1-item-1'
);

DROP TEMPORARY TABLE prompt_micro_preference_reframes;

COMMIT;
