-- Polish remaining awkward prompt questions that sounded too mechanical or over-literal.
-- This migration updates by prompt id so it can repair databases where older wording was already applied.

START TRANSACTION;

CREATE TEMPORARY TABLE prompt_question_polish_075 (
    id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci PRIMARY KEY,
    question_en TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    question_ko TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    tip TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
);

INSERT INTO prompt_question_polish_075 (id, question_en, question_ko, tip) VALUES
    ('prompt-routine-2009', 'What part of your morning routine helps you feel ready for the day?', '아침 루틴 중 어떤 부분이 하루를 준비됐다고 느끼게 해 주나요?', '아침에 하는 행동 하나를 말하고, 그 행동이 하루 시작에 왜 도움이 되는지 덧붙여 보세요.'),
    ('prompt-routine-2013', 'What do you do at the end of your morning routine to feel ready for the day?', '하루를 준비됐다고 느끼기 위해 아침 루틴의 마지막에 무엇을 하나요?', '마지막에 하는 행동을 말하고, 그 행동 뒤에 왜 준비가 끝난 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-routine-2025', 'What part of your commute makes it feel easier or more comfortable?', '이동할 때 어떤 부분이 더 편하거나 수월하게 느껴지나요?', '이동 중 행동이나 선택 하나를 말하고, 왜 이동이 편해지는지 덧붙여 보세요.'),
    ('prompt-routine-2030', 'What do you do when your commute is almost finished?', '이동이 거의 끝날 때 보통 무엇을 하나요?', '도착 전후에 하는 행동을 말하고, 그 행동이 다음 일정에 왜 도움이 되는지 함께 말해 보세요.'),
    ('prompt-routine-2043', 'What do you do during a short break to feel refreshed?', '짧은 휴식 시간에 상쾌해지기 위해 무엇을 하나요?', '짧게 하는 행동을 말하고, 그 행동이 왜 기분 전환에 도움이 되는지 덧붙여 보세요.'),
    ('prompt-routine-2057', 'What helps lunch or snack time feel relaxed during your day?', '하루 중 점심이나 간식 시간이 편하게 느껴지도록 무엇이 도움이 되나요?', '먹는 상황과 도움이 되는 행동을 함께 말하고, 왜 편해지는지 덧붙여 보세요.'),
    ('prompt-routine-2071', 'What do you do after coming home to switch into rest mode?', '집에 돌아온 뒤 쉬는 모드로 바꾸기 위해 무엇을 하나요?', '집에 오자마자 하는 행동을 말하고, 왜 쉬는 느낌이 드는지 함께 말해 보세요.'),
    ('prompt-routine-2086', 'What chore or kitchen task feels easiest for you, and why?', '집안일이나 주방 일 중 가장 시작하기 쉬운 것은 무엇인가요? 이유도 말해 주세요.', '일 하나를 고르고, 왜 부담이 적거나 쉽게 끝낼 수 있는지 덧붙여 보세요.'),
    ('prompt-routine-2102', 'How do you usually rest in the evening, and why does it work for you?', '저녁에는 보통 어떻게 쉬나요? 왜 나에게 잘 맞나요?', '쉬는 행동과 시간대를 말하고, 그 방식이 왜 편안한지 함께 말해 보세요.'),
    ('prompt-routine-2119', 'What do you like to do at home on the weekend, and why?', '주말에 집에서는 무엇을 하는 것을 좋아하나요? 이유도 말해 주세요.', '집에서 하는 활동을 말하고, 주말에 왜 잘 맞는지 덧붙여 보세요.'),
    ('prompt-routine-2131', 'What phone habit helps your day feel smoother?', '하루를 더 수월하게 만드는 휴대폰 습관은 무엇인가요?', '휴대폰으로 하는 행동 하나를 말하고, 그 습관이 왜 하루에 도움이 되는지 함께 말해 보세요.'),
    ('prompt-routine-2409', 'What do you do to feel comfortable on a rainy or cold day?', '비 오거나 추운 날에 편하게 지내기 위해 무엇을 하나요?', '날씨 상황을 먼저 말하고, 그때 하는 행동이 왜 도움이 되는지 덧붙여 보세요.'),
    ('prompt-routine-2414', 'What do you do at the end of a rainy or cold day to feel settled?', '비 오거나 추운 하루의 끝에 마음이 정리되도록 무엇을 하나요?', '하루 끝에 하는 행동을 말하고, 왜 몸이나 마음이 편해지는지 함께 말해 보세요.'),
    ('prompt-routine-2424', 'What helps you finish a quick errand or store stop smoothly?', '짧은 볼일이나 가게 방문을 수월하게 끝내는 데 무엇이 도움이 되나요?', '볼일 상황과 도움이 되는 행동을 함께 말하고, 왜 시간이 줄거나 편해지는지 덧붙여 보세요.'),
    ('prompt-routine-2429', 'What do you do after a quick errand or store stop before moving on?', '짧은 볼일이나 가게 방문을 마친 뒤 다음 일을 하기 전에 무엇을 하나요?', '마친 뒤 하는 행동을 말하고, 그 행동이 다음 일정에 왜 도움이 되는지 함께 말해 보세요.'),
    ('prompt-routine-2431', 'How do you choose what to order at a cafe or bakery, and why?', '카페나 빵집에서 무엇을 주문할지 어떻게 고르나요? 이유도 말해 주세요.', '무엇을 보고 고르는지 말하고, 그 기준이 왜 나에게 잘 맞는지 덧붙여 보세요.'),
    ('prompt-routine-2439', 'What do you like about visiting a cafe or bakery, and why?', '카페나 빵집에 갈 때 어떤 점이 좋나요? 이유도 말해 주세요.', '장소에서 좋아하는 점 하나를 말하고, 왜 그 시간이 편하거나 즐거운지 함께 말해 보세요.'),
    ('prompt-routine-2444', 'What do you do before leaving a cafe or bakery?', '카페나 빵집을 떠나기 전에 보통 무엇을 하나요?', '나가기 전에 하는 행동을 말하고, 그 행동이 왜 깔끔하거나 편한지 덧붙여 보세요.'),
    ('prompt-routine-2454', 'What part of a walk or light exercise helps you feel good?', '산책이나 가벼운 운동 중 어떤 부분이 기분을 좋게 하나요?', '걷는 시간, 장소, 움직임 중 하나를 말하고, 왜 기분이 좋아지는지 함께 말해 보세요.'),
    ('prompt-routine-2460', 'What do you do after a walk or light exercise to cool down?', '산책이나 가벼운 운동 뒤에 몸을 진정시키기 위해 무엇을 하나요?', '운동 뒤에 하는 행동을 말하고, 왜 몸이 편해지는지 덧붙여 보세요.'),
    ('prompt-routine-2465', 'What do you do after washing up to feel ready for rest or sleep?', '씻고 난 뒤 쉬거나 잘 준비가 됐다고 느끼기 위해 무엇을 하나요?', '씻고 난 뒤 하는 행동을 말하고, 그 행동이 쉬거나 잠드는 데 왜 도움이 되는지 함께 말해 보세요.'),
    ('prompt-routine-2469', 'What helps you get ready for bed comfortably?', '잠잘 준비를 편하게 하는 데 무엇이 도움이 되나요?', '잠들기 전 하는 행동이나 준비를 말하고, 왜 편안해지는지 덧붙여 보세요.'),
    ('prompt-routine-2475', 'What is the last thing you do before bed, and how does it help you relax?', '잠들기 전 마지막으로 무엇을 하나요? 그것이 긴장을 푸는 데 어떻게 도움이 되나요?', '마지막 행동을 말하고, 그 행동이 잠들기 전에 왜 마음을 편하게 하는지 함께 말해 보세요.'),
    ('prompt-preference-2231', 'What writing tool do you like to use when studying, and why?', '공부할 때 어떤 필기구를 즐겨 사용하나요? 이유도 말해 주세요.', '필기구 이름만 말하지 말고, 어떤 공부 상황에서 왜 편한지 함께 말해 보세요.'),
    ('prompt-preference-2232', 'When do you use an eraser while studying, and how does it help?', '공부할 때 지우개를 언제 사용하나요? 어떻게 도움이 되나요?', '틀린 부분을 고치거나 정리하는 상황을 말해 보세요.'),
    ('prompt-preference-2233', 'How do you use a highlighter when you study?', '공부할 때 형광펜을 어떻게 사용하나요?', '무엇을 표시하는지와 기억하는 데 왜 도움이 되는지 덧붙여 보세요.'),
    ('prompt-preference-2234', 'What do you write on sticky notes when studying or working?', '공부하거나 일할 때 포스트잇에 무엇을 적나요?', '적는 내용과 붙여 두는 장소를 함께 말해 보세요.'),
    ('prompt-preference-2235', 'How do you use a planner for study or work?', '공부나 일을 위해 플래너를 어떻게 사용하나요?', '적는 일정이나 확인하는 시간을 함께 말해 보세요.'),
    ('prompt-preference-2236', 'When do you use a bookmark while reading or studying?', '읽거나 공부할 때 책갈피를 언제 사용하나요?', '어디까지 읽었는지 표시하는 상황과 편한 점을 말해 보세요.'),
    ('prompt-preference-2237', 'How do you organize your desk before studying or working?', '공부하거나 일하기 전에 책상을 어떻게 정리하나요?', '치우는 물건이나 꺼내 두는 도구를 함께 말해 보세요.'),
    ('prompt-preference-2238', 'When do you use a ruler for school or work?', '학교나 일에서 자를 언제 사용하나요?', '선을 긋거나 정리하는 상황을 말하고 왜 필요한지 덧붙여 보세요.'),
    ('prompt-preference-2239', 'How do you organize papers for school or work?', '학교나 일에 필요한 종이를 어떻게 정리하나요?', '파일이나 폴더를 쓰는 방식과 찾기 쉬운 이유를 말해 보세요.'),
    ('prompt-preference-2240', 'What do you keep in a pouch for school or work?', '학교나 일을 위한 파우치에는 무엇을 넣어 두나요?', '넣어 두는 물건과 필요할 때 찾기 쉬운 이유를 말해 보세요.'),
    ('prompt-preference-2241', 'What keyboard setup helps you type comfortably?', '어떤 키보드 설정이나 배치가 타자를 편하게 해 주나요?', '크기, 위치, 언어 설정처럼 편해지는 점을 하나 말해 보세요.'),
    ('prompt-preference-2242', 'What mouse feels comfortable when you study or work?', '공부하거나 일할 때 어떤 마우스가 편하게 느껴지나요?', '모양만 말하지 말고, 오래 사용할 때 왜 편한지 덧붙여 보세요.'),
    ('prompt-preference-2243', 'How do you use a timer when studying or working?', '공부하거나 일할 때 타이머를 어떻게 사용하나요?', '언제 맞추는지와 집중하는 데 왜 도움이 되는지 함께 말해 보세요.'),
    ('prompt-preference-2246', 'What T-shirt do you wear on a normal day, and why?', '평범한 하루에는 어떤 티셔츠를 입나요? 이유도 말해 주세요.', '색만 말하지 말고, 편한 점이나 입는 상황을 함께 말해 보세요.'),
    ('prompt-preference-2247', 'When do you like to wear a hoodie, and why?', '후드티는 언제 입는 것을 좋아하나요? 이유도 말해 주세요.', '날씨나 장소를 말하고, 왜 편한지 덧붙여 보세요.'),
    ('prompt-preference-2248', 'What socks feel comfortable for a long day, and why?', '긴 하루를 보낼 때 어떤 양말이 편하게 느껴지나요? 이유도 말해 주세요.', '무늬보다 착용감이나 활동 상황을 중심으로 말해 보세요.'),
    ('prompt-preference-2249', 'What sneakers do you wear for daily walking, and why?', '일상적으로 걸을 때 어떤 운동화를 신나요? 이유도 말해 주세요.', '걷는 상황과 오래 신어도 편한 이유를 덧붙여 보세요.'),
    ('prompt-preference-2250', 'When do you wear a hat on a sunny day?', '햇볕이 강한 날 모자는 언제 쓰나요?', '가는 장소와 햇볕을 피하는 데 도움이 되는 이유를 말해 보세요.'),
    ('prompt-preference-2251', 'When do you wear a scarf in winter, and how does it help?', '겨울에는 목도리를 언제 두르나요? 어떻게 도움이 되나요?', '날씨나 이동 상황을 말하고 따뜻해지는 점을 덧붙여 보세요.'),
    ('prompt-preference-2252', 'What watch or accessory do you wear often, and why?', '자주 착용하는 시계나 액세서리는 무엇인가요? 이유도 말해 주세요.', '색보다 자주 쓰는 상황과 편한 점을 말해 보세요.'),
    ('prompt-preference-2253', 'When do you wear slippers at home, and why?', '집에서 실내화를 언제 신나요? 이유도 말해 주세요.', '신는 장소와 발이 편해지는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2254', 'When would you wear a raincoat, and how would it help?', '비옷은 언제 입고 싶나요? 어떻게 도움이 되나요?', '비 오는 상황과 옷이 젖지 않는 점을 말해 보세요.'),
    ('prompt-preference-2255', 'What do you wear to bed when you want to sleep comfortably, and why?', '편하게 자고 싶을 때 잠자리에 무엇을 입나요? 이유도 말해 주세요.', '무엇을 입는지와 잠들기 전에 왜 몸이 편해지는지 말해 보세요.'),
    ('prompt-preference-2256', 'When do you tie your hair, and what helps it feel comfortable?', '머리를 언제 묶나요? 무엇이 편하게 느껴지게 하나요?', '운동, 공부, 외출 같은 상황과 편한 이유를 함께 말해 보세요.'),
    ('prompt-preference-2257', 'What umbrella do you use on a rainy day, and why?', '비 오는 날 어떤 우산을 사용하나요? 이유도 말해 주세요.', '우산의 크기나 들고 다니기 편한 점을 덧붙여 보세요.'),
    ('prompt-preference-2258', 'What jacket do you wear on an ordinary day outside, and why?', '평범하게 외출하는 날 어떤 재킷을 입나요? 이유도 말해 주세요.', '날씨나 이동 상황을 말하고, 왜 입기 편한지 덧붙여 보세요.'),
    ('prompt-preference-2261', 'What blanket helps you feel comfortable at home, and when do you use it?', '집에서 편안하게 느끼게 해 주는 담요는 어떤 것인가요? 언제 사용하나요?', '담요의 특징과 사용하는 상황을 함께 말하고, 왜 편안한지 덧붙여 보세요.'),
    ('prompt-preference-2262', 'What pillow helps you rest better at home, and why?', '집에서 더 잘 쉬게 해 주는 베개는 어떤 것인가요? 이유도 말해 주세요.', '베개의 특징을 말하고, 쉬거나 잘 때 왜 도움이 되는지 덧붙여 보세요.'),
    ('prompt-preference-2263', 'What mug do you like to use at home, and when do you use it?', '집에서 어떤 머그컵을 즐겨 사용하나요? 언제 사용하나요?', '컵의 특징과 사용하는 순간을 함께 말해 보세요.'),
    ('prompt-preference-2265', 'What lamp or light helps your room feel comfortable, and why?', '방을 편안하게 느끼게 해 주는 조명은 어떤 것인가요? 이유도 말해 주세요.', '조명의 위치나 밝기를 말하고, 왜 편하게 느껴지는지 덧붙여 보세요.'),
    ('prompt-preference-2266', 'Where do you keep a water bottle at home, and how does it help you?', '집에서 물병을 어디에 두나요? 그것이 어떻게 도움이 되나요?', '물병을 두는 장소와 자주 쓰는 순간을 함께 말해 보세요.'),
    ('prompt-preference-2267', 'How does your desk mat help you study or work at home?', '데스크 매트가 집에서 공부하거나 일할 때 어떻게 도움이 되나요?', '데스크 매트의 쓰임과 책상 위에서 편해지는 점을 말해 보세요.'),
    ('prompt-preference-2268', 'What helps your chair feel more comfortable when you sit for a long time?', '오래 앉아 있을 때 의자를 더 편하게 해 주는 것은 무엇인가요?', '쿠션이나 자세처럼 편해지는 요소를 하나 말해 보세요.'),
    ('prompt-preference-2269', 'How do you use a wall calendar at home, and why is it helpful?', '집에서 벽 달력을 어떻게 사용하나요? 왜 도움이 되나요?', '확인하는 일정이나 사용하는 순간을 함께 말해 보세요.'),
    ('prompt-preference-2270', 'When do you use a small fan in your room, and how does it help?', '방에서 작은 선풍기를 언제 사용하나요? 어떻게 도움이 되나요?', '날씨나 시간대를 말하고, 왜 편해지는지 덧붙여 보세요.'),
    ('prompt-preference-2272', 'What do you keep in a storage basket at home, and why?', '집에서 수납 바구니에 무엇을 보관하나요? 이유도 말해 주세요.', '무엇을 넣는지와 정리가 쉬워지는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2274', 'What small item makes your room feel more relaxing, and why?', '방을 더 편안하게 느끼게 해 주는 작은 물건은 무엇인가요? 이유도 말해 주세요.', '물건 하나를 고르고, 방 분위기가 어떻게 달라지는지 덧붙여 보세요.'),
    ('prompt-preference-2275', 'What do you keep near your bed, and how does it help you?', '침대 근처에 무엇을 두나요? 그것이 어떻게 도움이 되나요?', '자기 전이나 일어난 뒤에 쓰는 물건을 말해 보세요.'),
    ('prompt-preference-2291', 'What phone wallpaper do you like to use, and why?', '어떤 휴대폰 배경화면을 즐겨 사용하나요? 이유도 말해 주세요.', '배경화면의 느낌과 볼 때 드는 기분을 함께 말해 보세요.'),
    ('prompt-preference-2292', 'What alarm sound helps you wake up, and why?', '일어나는 데 도움이 되는 알람 소리는 어떤 것인가요? 이유도 말해 주세요.', '소리의 느낌과 아침에 왜 도움이 되는지 덧붙여 보세요.'),
    ('prompt-preference-2293', 'How do you check your schedule on your phone?', '휴대폰으로 일정을 어떻게 확인하나요?', '어떤 앱이나 화면을 보는지, 언제 확인하는지 함께 말해 보세요.'),
    ('prompt-preference-2294', 'When do you write quick notes on your phone?', '휴대폰에 짧은 메모를 언제 적나요?', '메모하는 상황과 적는 내용을 함께 말해 보세요.'),
    ('prompt-preference-2295', 'When do you use stickers in messages, and why?', '메시지에서 스티커를 언제 사용하나요? 이유도 말해 주세요.', '누구에게 보내는지와 어떤 느낌을 전하고 싶은지 말해 보세요.'),
    ('prompt-preference-2296', 'How do you choose music on your phone during the day?', '하루 중 휴대폰으로 음악을 어떻게 고르나요?', '듣는 시간대나 상황을 말하고, 왜 그 음악을 고르는지 덧붙여 보세요.'),
    ('prompt-preference-2297', 'What photo filter do you use, and when?', '어떤 사진 필터를 사용하나요? 언제 사용하나요?', '필터의 느낌과 사진을 더 마음에 들게 하는 이유를 말해 보세요.'),
    ('prompt-preference-2298', 'How do you choose a route on your phone when you go somewhere?', '어딘가 갈 때 휴대폰으로 경로를 어떻게 고르나요?', '빠른 길, 편한 길, 환승 같은 기준을 함께 말해 보세요.'),
    ('prompt-preference-2299', 'When do you check the weather on your phone, and why?', '휴대폰으로 날씨를 언제 확인하나요? 이유도 말해 주세요.', '확인하는 시간과 그 정보가 어떤 준비에 도움이 되는지 말해 보세요.'),
    ('prompt-preference-2300', 'What keyboard setting makes typing easier for you?', '어떤 키보드 설정이 타자를 더 쉽게 해 주나요?', '크기, 언어, 테마처럼 편해지는 설정을 하나 말해 보세요.'),
    ('prompt-preference-2301', 'What phone shortcut do you use often, and why?', '자주 사용하는 휴대폰 바로가기는 무엇인가요? 이유도 말해 주세요.', '어떤 기능을 빠르게 여는지와 왜 편한지 함께 말해 보세요.'),
    ('prompt-preference-2302', 'What playlist do you open often on your phone, and when?', '휴대폰에서 자주 여는 플레이리스트는 무엇인가요? 언제 듣나요?', '음악을 듣는 상황과 그 플레이리스트가 잘 맞는 이유를 말해 보세요.'),
    ('prompt-preference-2303', 'What reminders do you set on your phone, and why?', '휴대폰에 어떤 리마인더를 설정하나요? 이유도 말해 주세요.', '잊지 않으려는 일과 알림이 도움이 되는 순간을 함께 말해 보세요.'),
    ('prompt-preference-2304', 'What phone widget do you check often, and why?', '자주 확인하는 휴대폰 위젯은 무엇인가요? 이유도 말해 주세요.', '날씨, 일정, 메모처럼 자주 보는 정보를 말해 보세요.'),
    ('prompt-preference-2306', 'Where do you like to sit in a small park near your neighborhood, and why?', '동네 작은 공원에서는 어디에 앉는 것을 좋아하나요? 이유도 말해 주세요.', '장소 이름만 말하지 말고, 언제 앉는지와 그 자리가 왜 쉬기 좋은지 함께 말해 보세요.'),
    ('prompt-preference-2307', 'What do you usually buy at a convenience store near you, and why is it useful?', '동네 편의점에서는 보통 무엇을 사나요? 왜 유용한가요?', '무엇을 사는지 말하고, 급하거나 필요한 순간에 왜 도움이 되는지 덧붙여 보세요.'),
    ('prompt-preference-2309', 'When would you stop by a flower stand near home, and what would you choose?', '집 근처 꽃가게나 꽃 판매대에는 언제 들르고, 무엇을 고르고 싶나요?', '언제 들르는지 먼저 말하고, 어떤 꽃이나 물건을 고르는지와 이유를 함께 말해 보세요.'),
    ('prompt-preference-2310', 'How do you use a bus stop near home in your daily routine?', '집 근처 버스 정류장을 일상에서 어떻게 이용하나요?', '언제 이용하는지와 어디로 갈 때 도움이 되는지 한 문장으로 말해 보세요.'),
    ('prompt-preference-2311', 'Where do you like to sit on a train or bus, and why?', '기차나 버스에서는 어디에 앉는 것을 좋아하나요? 이유도 말해 주세요.', '자리 위치를 말하고, 그 자리가 왜 편하거나 이동 중에 좋은지 함께 말해 보세요.'),
    ('prompt-preference-2312', 'What fruit would you buy from a nearby fruit stand, and when would you eat it?', '집 근처 과일가게에서는 어떤 과일을 사고 싶나요? 언제 먹고 싶나요?', '과일 이름만 말하지 말고, 언제 먹는지와 왜 그 과일을 고르는지 함께 말해 보세요.'),
    ('prompt-preference-2315', 'What small place near home is useful when you need something quickly?', '급하게 필요한 것이 있을 때 집 근처 어떤 작은 장소가 유용한가요?', '장소를 하나 고르고, 어떤 상황에서 빠르게 도움이 되는지 말해 보세요.'),
    ('prompt-preference-2316', 'Where do you like to sit when you rest outside, and why?', '밖에서 쉴 때 어디에 앉는 것을 좋아하나요? 이유도 말해 주세요.', '앉는 장소와 상황을 말하고, 그곳이 왜 쉬기 좋게 느껴지는지 덧붙여 보세요.'),
    ('prompt-preference-2320', 'Where do you go near your neighborhood when you want a little fresh air?', '잠깐 바람을 쐬고 싶을 때 동네 어디로 가나요?', '어디로 가는지 말하고, 그 장소가 왜 기분 전환에 도움이 되는지 함께 말해 보세요.'),
    ('prompt-preference-2321', 'What simple puzzle or game do you enjoy in your free time, and why?', '여가 시간에는 어떤 간단한 퍼즐이나 게임을 즐기나요? 이유도 말해 주세요.', '활동 이름만 말하지 말고, 언제 하는지와 왜 재미있거나 편한지 함께 말해 보세요.'),
    ('prompt-preference-2324', 'What podcast topic do you enjoy in your free time, and why?', '여가 시간에는 어떤 주제의 팟캐스트를 즐기나요? 이유도 말해 주세요.', '주제와 듣는 상황을 함께 말하고, 왜 그 주제가 흥미롭거나 편한지 덧붙여 보세요.'),
    ('prompt-preference-2325', 'What simple creative activity helps you relax, and what do you use for it?', '긴장을 풀 때 어떤 간단한 창작 활동을 하나요? 무엇을 사용하나요?', '활동과 도구를 함께 말하고, 그 활동이 왜 긴장을 푸는 데 도움이 되는지 덧붙여 보세요.'),
    ('prompt-preference-2326', 'What simple craft would you like to try in your free time, and what would you use?', '여가 시간에 어떤 간단한 만들기를 해 보고 싶나요? 무엇을 사용하고 싶나요?', '만들기 활동과 재료를 함께 말하고, 왜 해 보고 싶은지 한 문장 덧붙여 보세요.'),
    ('prompt-preference-2327', 'How do you like to edit photos before you save or share them?', '사진을 저장하거나 공유하기 전에 어떻게 보정하는 것을 좋아하나요?', '어떤 보정을 하는지 말하고, 사진이 왜 더 마음에 드는지 함께 말해 보세요.'),
    ('prompt-preference-2328', 'What quick activity do you do during a ten-minute break, and why?', '10분 정도 쉴 때 어떤 짧은 활동을 하나요? 이유도 말해 주세요.', '짧게 할 수 있는 활동을 말하고, 그 활동이 왜 쉬는 시간에 잘 맞는지 덧붙여 보세요.'),
    ('prompt-preference-2329', 'What indoor hobby feels good on a rainy day, and why?', '비 오는 날에는 어떤 실내 취미가 좋게 느껴지나요? 이유도 말해 주세요.', '취미 이름과 날씨 상황을 함께 말하고, 왜 비 오는 날에 잘 맞는지 말해 보세요.'),
    ('prompt-preference-2330', 'What sound or music helps you relax in your free time?', '여가 시간에 긴장을 푸는 데 도움이 되는 소리나 음악은 무엇인가요?', '어떤 소리인지 말하고, 언제 들으면 편안해지는지 함께 말해 보세요.'),
    ('prompt-preference-2331', 'What indoor activity do you enjoy on a hot day, and why?', '더운 날에는 어떤 실내 활동을 즐기나요? 이유도 말해 주세요.', '활동과 날씨 상황을 함께 말하고, 왜 더운 날에 잘 맞는지 덧붙여 보세요.'),
    ('prompt-preference-2333', 'What short video helps you learn something new, and why do you watch it?', '새로운 것을 배울 때 어떤 짧은 영상을 보나요? 왜 그 영상을 보나요?', '영상 주제를 말하고, 짧은 시간에 배우기 좋은 이유를 함께 말해 보세요.'),
    ('prompt-preference-2501', 'What water bottle do you carry during the day, and how does it help?', '하루 중 어떤 물병을 들고 다니나요? 어떻게 도움이 되나요?', '물병을 쓰는 상황과 물을 마시기 쉬워지는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2502', 'When do you refill your tumbler during the day?', '하루 중 텀블러를 언제 다시 채우나요?', '다시 채우는 시간이나 장소를 말하고, 왜 편한지 덧붙여 보세요.'),
    ('prompt-preference-2503', 'What sparkling water flavor do you like, and when do you drink it?', '어떤 탄산수 맛을 좋아하나요? 언제 마시나요?', '맛과 마시는 상황을 함께 말해 보세요.'),
    ('prompt-preference-2511', 'When do you use a reusable cup outside, and why?', '밖에서 다회용 컵을 언제 사용하나요? 이유도 말해 주세요.', '사용하는 상황과 컵을 쓰면 좋은 점을 말해 보세요.'),
    ('prompt-preference-2512', 'What do you drink after light exercise, and how does it help?', '가벼운 운동 뒤에 무엇을 마시나요? 어떻게 도움이 되나요?', '운동 뒤 몸이 어떻게 편해지는지 함께 말해 보세요.'),
    ('prompt-preference-2513', 'What cold drink do you choose on a hot day, and why?', '더운 날에는 어떤 차가운 음료를 고르나요? 이유도 말해 주세요.', '음료 이름과 더운 날에 잘 맞는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2515', 'What do you drink when you get home on a warm day, and why?', '따뜻한 날 집에 돌아오면 무엇을 마시나요? 이유도 말해 주세요.', '집에 돌아온 순간과 음료가 주는 느낌을 함께 말해 보세요.'),
    ('prompt-preference-2516', 'How do you set up your backpack for a busy day?', '바쁜 하루를 위해 백팩을 어떻게 챙기나요?', '가방 안에 넣는 물건과 하루가 편해지는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2517', 'When do you use a tote bag for a short trip?', '짧게 나갈 때 토트백을 언제 사용하나요?', '어디에 갈 때 쓰는지와 무엇을 넣는지 말해 보세요.'),
    ('prompt-preference-2518', 'What do you keep in a small pouch in your bag?', '가방 속 작은 파우치에는 무엇을 넣어 두나요?', '넣어 두는 물건과 찾기 쉬워지는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2519', 'What do you keep in your wallet for daily use?', '매일 쓰는 지갑에는 무엇을 넣어 두나요?', '자주 쓰는 카드나 물건을 말하고, 언제 필요한지 덧붙여 보세요.'),
    ('prompt-preference-2521', 'Where do you keep your water bottle in your bag?', '가방 안에서 물병을 어디에 넣어 두나요?', '넣는 위치와 꺼내기 편한 이유를 함께 말해 보세요.'),
    ('prompt-preference-2522', 'How do you organize your bag so it is easy to open and close?', '열고 닫기 편하도록 가방을 어떻게 정리하나요?', '지퍼나 수납 위치처럼 사용이 쉬워지는 점을 말해 보세요.'),
    ('prompt-preference-2523', 'When do you use a cardholder, and why?', '카드지갑을 언제 사용하나요? 이유도 말해 주세요.', '지갑 대신 카드지갑을 쓰는 상황과 편한 점을 말해 보세요.'),
    ('prompt-preference-2524', 'What makes a bag comfortable to carry for a long time?', '가방을 오래 들고 다닐 때 무엇이 편하게 해 주나요?', '끈, 무게, 크기처럼 편함을 주는 요소를 말해 보세요.'),
    ('prompt-preference-2525', 'What everyday bag do you use most, and why?', '가장 자주 쓰는 일상 가방은 무엇인가요? 이유도 말해 주세요.', '가방 종류와 자주 쓰는 상황을 함께 말해 보세요.'),
    ('prompt-preference-2526', 'When do you use a foldable shopping bag?', '접이식 장바구니를 언제 사용하나요?', '사용하는 장소와 편한 이유를 덧붙여 보세요.'),
    ('prompt-preference-2528', 'What do you keep in a pouch for pens or cables?', '펜이나 케이블 파우치에는 무엇을 넣어 두나요?', '정리되는 물건과 필요할 때 찾기 쉬운 이유를 말해 보세요.'),
    ('prompt-preference-2530', 'What small bag do you use for a quick trip outside?', '잠깐 외출할 때 어떤 작은 가방을 사용하나요?', '어디에 갈 때 쓰는지와 무엇을 넣는지 함께 말해 보세요.'),
    ('prompt-preference-2531', 'What do you keep in a storage box at home?', '집에서 수납 상자에 무엇을 보관하나요?', '무엇을 넣는지와 정리가 쉬워지는 이유를 말해 보세요.'),
    ('prompt-preference-2532', 'How do you hang your daily clothes at home?', '집에서 매일 입는 옷을 어떻게 걸어 두나요?', '옷을 찾기 쉬워지는 방식이나 이유를 덧붙여 보세요.'),
    ('prompt-preference-2533', 'How do you organize a drawer so it is easy to use?', '서랍을 쓰기 편하게 어떻게 정리하나요?', '넣는 물건과 나누는 방식을 함께 말해 보세요.'),
    ('prompt-preference-2535', 'What small items do you keep in a box at home?', '집에서 작은 상자에 어떤 물건을 넣어 두나요?', '작은 물건을 정리하면 어떤 점이 편해지는지 덧붙여 보세요.'),
    ('prompt-preference-2536', 'What do you use to clean your desk before studying?', '공부하기 전에 책상을 정리하거나 닦을 때 무엇을 사용하나요?', '공부 전 책상 정리 상황에서 사용하는 것과 이유를 말해 보세요.'),
    ('prompt-preference-2537', 'What small cleaning job at home is easiest for you to start, and why?', '집에서 시작하기 가장 쉬운 작은 청소는 무엇인가요? 이유도 말해 주세요.', '청소 행동 하나를 고르고 왜 부담 없이 시작할 수 있는지 덧붙여 보세요.'),
    ('prompt-preference-2538', 'What sponge or tool do you use for kitchen cleaning?', '주방 청소에는 어떤 스펀지나 도구를 사용하나요?', '어떤 일을 할 때 쓰는지와 왜 편한지 함께 말해 보세요.'),
    ('prompt-preference-2539', 'What storage space helps make your room easier to use?', '방을 더 쓰기 편하게 만들어 주는 수납 공간은 어떤 것인가요?', '무엇을 어디에 두고 왜 찾기 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2541', 'How do you organize a bathroom drawer so it is easy to use?', '욕실 서랍을 쓰기 편하게 어떻게 정리하나요?', '자주 쓰는 물건과 꺼내기 쉬운 이유를 함께 말해 보세요.'),
    ('prompt-preference-2545', 'Where do you keep bags or keys near the door?', '문 근처에 가방이나 열쇠를 어디에 두나요?', '나가기 전 찾기 쉬워지는 이유를 덧붙여 보세요.'),
    ('prompt-preference-2546', 'How do you charge your phone at home so it is easy to use?', '집에서 휴대폰을 쓰기 편하게 충전하려면 어떻게 하나요?', '충전 위치나 시간대를 말하고, 왜 편한지 덧붙여 보세요.'),
    ('prompt-preference-2547', 'What cable setup makes your daily devices easier to use?', '매일 쓰는 기기를 더 편하게 사용하게 해 주는 케이블 구성은 무엇인가요?', '어떤 불편함을 줄여 주는지 함께 말해 보세요.'),
    ('prompt-preference-2548', 'When do you play background music at home, and what do you use?', '집에서 배경음악을 언제 틀고, 무엇으로 듣나요?', '시간대나 상황을 말하고, 왜 분위기가 좋아지는지 덧붙여 보세요.'),
    ('prompt-preference-2549', 'When do you use a desk fan on warm days?', '더운 날 책상 선풍기를 언제 사용하나요?', '사용하는 상황과 왜 시원하거나 편한지 말해 보세요.'),
    ('prompt-preference-2550', 'How do you use alarms or reminders to stay on track during the day?', '하루 일정을 놓치지 않기 위해 알람이나 리마인더를 어떻게 사용하나요?', '언제 알람을 쓰는지 말하고, 그 설정이 루틴을 지키는 데 왜 도움이 되는지 덧붙여 보세요.'),
    ('prompt-preference-2551', 'How do you use a phone stand on your desk?', '책상 위 휴대폰 거치대를 어떻게 사용하나요?', '언제 올려 두는지와 어떤 점이 편해지는지 말해 보세요.'),
    ('prompt-preference-2552', 'What kind of light do you use when you read at night, and why?', '밤에 책을 읽을 때 어떤 조명을 사용하나요? 이유도 말해 주세요.', '조명의 밝기나 위치를 말하고, 밤에 읽을 때 왜 편한지 덧붙여 보세요.'),
    ('prompt-preference-2553', 'When do you use a timer for short tasks?', '짧은 일을 할 때 타이머를 언제 사용하나요?', '타이머를 쓰는 일과 집중에 도움이 되는 이유를 말해 보세요.'),
    ('prompt-preference-2554', 'When do you use a humidifier at home, and how does it help?', '집에서 가습기를 언제 사용하나요? 어떻게 도움이 되나요?', '계절이나 시간대를 말하고, 공기가 어떻게 편해지는지 덧붙여 보세요.'),
    ('prompt-preference-2555', 'Where do you use a power strip at home, and why?', '집에서 멀티탭을 어디에 사용하나요? 이유도 말해 주세요.', '연결하는 기기와 사용이 편해지는 이유를 함께 말해 보세요.'),
    ('prompt-preference-2556', 'What light helps you read at home, and when do you use it?', '집에서 책을 읽을 때 도움이 되는 조명은 무엇인가요? 언제 사용하나요?', '어디에 두고 쓰는지와 눈이 편한 이유를 말해 보세요.'),
    ('prompt-preference-2558', 'When do you use a portable fan, and why?', '휴대용 선풍기를 언제 사용하나요? 이유도 말해 주세요.', '밖이나 실내에서 쓰는 상황과 도움이 되는 이유를 말해 보세요.'),
    ('prompt-preference-2559', 'How do you use a tablet stand at home?', '집에서 태블릿 거치대를 어떻게 사용하나요?', '보는 영상이나 공부 상황을 말하고, 왜 편한지 덧붙여 보세요.'),
    ('prompt-preference-2560', 'When do you use a clip-on lamp at your desk or bed?', '책상이나 침대에서 집게형 조명을 언제 사용하나요?', '어떤 일을 할 때 쓰는지와 빛이 왜 도움이 되는지 말해 보세요.'),
    ('prompt-preference-2561', 'How do you store leftovers at home?', '집에서 남은 음식을 어떻게 보관하나요?', '보관 용기나 냉장고 위치를 말하고, 왜 편한지 덧붙여 보세요.'),
    ('prompt-preference-2563', 'What lunch container do you use away from home, and why is it comfortable?', '밖에서 먹을 때 어떤 도시락통이나 용기를 사용하나요? 왜 편한가요?', '용기 종류와 사용하는 상황을 함께 말하고, 먹거나 들고 다니기 편한 이유를 덧붙여 보세요.'),
    ('prompt-preference-2566', 'What helps you prepare food with less mess, and why?', '음식을 덜 지저분하게 준비하는 데 도움이 되는 것은 무엇인가요? 이유도 말해 주세요.', '도구나 습관 하나를 고르고 준비 과정이 어떻게 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2567', 'What cutting board do you use when cooking, and why?', '요리할 때 어떤 도마를 사용하나요? 이유도 말해 주세요.', '도마의 크기나 씻기 쉬운 점을 덧붙여 보세요.'),
    ('prompt-preference-2568', 'When do you use a kitchen towel, and how does it help?', '주방 수건을 언제 사용하나요? 어떻게 도움이 되나요?', '닦거나 정리하는 상황과 편해지는 점을 말해 보세요.'),
    ('prompt-preference-2569', 'When do you use a kettle at home, and what do you make?', '집에서 주전자를 언제 사용하나요? 무엇을 만드나요?', '차나 따뜻한 물처럼 만드는 것을 말하고, 그 순간을 덧붙여 보세요.'),
    ('prompt-preference-2570', 'When do you use a thermos for a warm drink?', '따뜻한 음료를 위해 보온병을 언제 사용하나요?', '어디에 가져가는지와 따뜻하게 유지되는 점을 말해 보세요.'),
    ('prompt-preference-2572', 'What helps you carry or store small sauces or snacks neatly?', '작은 소스나 간식을 깔끔하게 담거나 챙기는 데 도움이 되는 것은 무엇인가요?', '어떤 상황에서 준비나 정리가 쉬워지는지 말해 보세요.'),
    ('prompt-preference-2575', 'What small container do you use for sauces or snacks?', '소스나 간식을 담을 때 어떤 작은 용기를 사용하나요?', '담는 음식과 깔끔하게 챙길 수 있는 이유를 말해 보세요.');

UPDATE prompts p
JOIN prompt_question_polish_075 r ON r.id = p.id
SET p.question_en = r.question_en,
    p.question_ko = r.question_ko,
    p.tip = r.tip
WHERE p.is_active = 1;

DROP TEMPORARY TABLE prompt_question_polish_075;

COMMIT;
