const PROMPT_HINT_MEANING_MAP: Record<string, string> = {
  "relax": "휴식을 취하다",
  "wash the dishes": "설거지하다",
  "watch videos": "영상을 보다",
  "take a walk": "산책하다",
  "get ready for bed": "잠잘 준비를 하다",
  "after dinner": "저녁을 먹은 후에",
  "in the evening": "저녁 시간에",
  "before bed": "잠들기 전에",
  "most days": "대부분의 날에는",
  "right after i eat": "밥을 먹자마자",
  "spicy": "매콤한",
  "savory": "감칠맛 나는",
  "sweet": "달콤한",
  "comforting": "편안함을 주는",
  "delicious": "맛있는",
  "my favorite food": "내가 가장 좋아하는 음식",
  "one reason is": "한 가지 이유는",
  "i especially like": "나는 특히 좋아한다",
  "it tastes": "맛이 ~하다",
  "it reminds me of": "~을 떠올리게 한다",
  "rest": "쉬다",
  "meet friends": "친구를 만나다",
  "exercise": "운동하다",
  "study": "공부하다",
  "go out": "외출하다",
  "on weekends": "주말에는",
  "in the morning": "아침에",
  "in the afternoon": "오후에",
  "with my family": "가족과 함께",
  "most of the time": "대부분의 시간에는",
  "deadline": "마감일",
  "pressure": "압박감",
  "teamwork": "팀워크",
  "schedule": "일정",
  "solution": "해결책",
  "i deal with it by": "나는 그것을 ~하면서 해결한다",
  "one thing i do is": "내가 하는 한 가지는",
  "when this happens": "이런 일이 생기면",
  "step by step": "차근차근",
  "in the end": "결국에는",
  "culture": "문화",
  "scenery": "풍경",
  "landmark": "명소",
  "local food": "현지 음식",
  "explore": "탐험하다",
  "i want to visit": "방문하고 싶다",
  "i would love to": "정말 ~하고 싶다",
  "once i get there": "그곳에 도착하면",
  "i also want to": "나는 또한 ~하고 싶다",
  "because it looks": "~처럼 보여서",
  "consistency": "꾸준함",
  "routine": "루틴",
  "progress": "진전",
  "habit": "습관",
  "improve": "향상시키다",
  "every day": "매일",
  "little by little": "조금씩",
  "stick to it": "꾸준히 이어가다",
  "make time for": "~할 시간을 내다",
  "because it helps me": "그것이 나에게 도움이 되기 때문에",
  "connection": "연결감",
  "convenience": "편리함",
  "distance": "거리감",
  "misunderstanding": "오해",
  "communication": "소통",
  "on the one hand": "한편으로는",
  "on the other hand": "다른 한편으로는",
  "in some ways": "어떤 면에서는",
  "overall": "전반적으로",
  "at the same time": "동시에",
  "responsibility": "책임",
  "employees": "직원들",
  "community": "지역사회",
  "trust": "신뢰",
  "sustainability": "지속가능성",
  "in my opinion": "내 생각에는",
  "for example": "예를 들면",
  "they should": "그들은 ~해야 한다",
  "this matters because": "이것이 중요한 이유는",
  "one important role is": "한 가지 중요한 역할은",
  "belief": "믿음",
  "perspective": "관점",
  "realize": "깨닫다",
  "experience": "경험",
  "change": "변화",
  "over time": "시간이 지나면서",
  "because of": "~ 때문에",
  "after i experienced": "내가 ~을 겪은 후에",
  "now i see": "이제는 알겠다",
  "what changed my mind was": "내 생각을 바꾼 것은",
  "grab dinner": "저녁을 간단히 먹다",
  "work out": "운동하다",
  "unwind": "긴장을 풀다",
  "after work": "퇴근 후에",
  "when i get home": "집에 도착하면",
  "once i finish work": "일을 마치면",
  "destination": "여행지",
  "museum": "박물관",
  "food": "음식",
  "i want to go there because": "그곳에 가고 싶은 이유는",
  "so i can": "그래서 ~할 수 있다",
  "when i visit": "방문하면",
  "one thing i would do": "내가 하고 싶은 한 가지는",
  "practice": "연습하다",
  "confidence": "자신감",
  "goal": "목표",
  "i plan to": "~할 계획이다",
  "every week": "매주",
  "to get better at": "~을 더 잘하게 되기 위해",
  "because it will help me": "그것이 나에게 도움이 될 것이기 때문에"
};

function normalizePromptHintContent(value: string) {
  return value.trim().replace(/\s+/g, " ").toLowerCase();
}

export function getPromptHintMeaningFallback(content: string) {
  return PROMPT_HINT_MEANING_MAP[normalizePromptHintContent(content)] ?? null;
}
