from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import pymysql


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "infra" / "mysql" / "schema" / "042-reclassify-active-hint-phrases.sql"

MOVE_TO_PHRASE = {
    "wash the dishes",
    "watch videos",
    "take a walk",
    "get ready for bed",
    "meet friends",
    "go out",
    "grab dinner",
    "work out",
    "wake up",
    "get ready",
    "stay home",
    "watch shows",
    "sleep in",
    "tidy up",
}


def parse_env(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip()
    return data


def connect_local() -> pymysql.Connection:
    env = parse_env(ROOT / ".env")
    return pymysql.connect(
        host="127.0.0.1",
        port=3306,
        user=env["SPRING_DATASOURCE_USERNAME"],
        password=env["SPRING_DATASOURCE_PASSWORD"],
        database="writeloop",
        charset="utf8mb4",
        autocommit=True,
    )


def sql_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def main() -> None:
    conn = connect_local()
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT p.id AS prompt_id,
                   p.question_en,
                   wh.id AS word_hint_id,
                   ph.id AS phrase_hint_id,
                   i.id AS item_id,
                   i.content,
                   i.display_order,
                   i.item_type
            FROM prompts p
            JOIN prompt_hints wh
              ON wh.prompt_id = p.id
             AND wh.hint_type = 'VOCAB_WORD'
             AND wh.is_active = 1
            JOIN prompt_hints ph
              ON ph.prompt_id = p.id
             AND ph.hint_type = 'VOCAB_PHRASE'
             AND ph.is_active = 1
            JOIN prompt_hint_items i
              ON i.hint_id = wh.id
             AND i.is_active = 1
            WHERE p.is_active = 1
              AND i.content IN %s
            ORDER BY p.id, i.display_order
            """,
            (tuple(sorted(MOVE_TO_PHRASE)),),
        )
        move_rows = cur.fetchall()

        cur.execute(
            """
            SELECT hint_id, id AS item_id, display_order
            FROM prompt_hint_items
            WHERE is_active = 1
            ORDER BY hint_id, display_order, id
            """
        )
        all_items = cur.fetchall()
    conn.close()

    items_by_hint: dict[str, list[tuple[str, int]]] = defaultdict(list)
    for hint_id, item_id, display_order in all_items:
        items_by_hint[hint_id].append((item_id, display_order))

    grouped_moves: dict[str, list[tuple[str, str, str, str, str, int, str]]] = defaultdict(list)
    for row in move_rows:
        grouped_moves[row[0]].append(row)

    statements: list[str] = [
        "-- Reclassify active action-like VOCAB_WORD items into VOCAB_PHRASE.",
        "-- Generated by scripts/generate_active_hint_phrase_reclass_042.py",
        "",
    ]

    move_count = 0
    for prompt_id, rows in grouped_moves.items():
        prompt_question = rows[0][1]
        word_hint_id = rows[0][2]
        phrase_hint_id = rows[0][3]
        moving_item_ids = {row[4] for row in rows}

        statements.append(f"-- {prompt_id}: {prompt_question}")

        phrase_items = [
            item_id for item_id, _display_order in items_by_hint[phrase_hint_id]
        ]
        for row in rows:
            item_id = row[4]
            content = row[5]
            item_type = row[7]
            phrase_items.append(item_id)
            new_display_order = len(phrase_items)
            statements.append("UPDATE prompt_hint_items")
            statements.append(
                f"SET hint_id = {sql_string(phrase_hint_id)},"
            )
            statements.append("    item_type = 'PHRASE',")
            statements.append(
                f"    display_order = {new_display_order}"
            )
            statements.append(
                f"WHERE id = {sql_string(item_id)}"
            )
            statements.append(
                f"  AND hint_id = {sql_string(word_hint_id)}"
            )
            statements.append(
                f"  AND item_type = {sql_string(item_type)}"
            )
            statements.append(
                f"  AND content = {sql_string(content)};"
            )
            statements.append("")
            move_count += 1

        remaining_word_items = [
            item_id
            for item_id, _display_order in items_by_hint[word_hint_id]
            if item_id not in moving_item_ids
        ]
        for new_display_order, item_id in enumerate(remaining_word_items, start=1):
            statements.append("UPDATE prompt_hint_items")
            statements.append(
                f"SET display_order = {new_display_order}"
            )
            statements.append(
                f"WHERE id = {sql_string(item_id)}"
            )
            statements.append(
                f"  AND hint_id = {sql_string(word_hint_id)};"
            )
            statements.append("")

    OUTPUT_PATH.write_text("\n".join(statements), encoding="utf-8")
    print(f"Prepared {move_count} hint-item moves across {len(grouped_moves)} prompts.")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
